### ISSUE TITLE
subscriptions not working

### ISSUE THREAD

**Issue by sailoog** [SignalK/signalk-server-node#100]
I can only subscribe to the entire data model but not to parts of it. Is this feature implemented?

**Comment by tkurki** [comment]
#35. Ancient, you are the first one to ask for it. Need to redo it.

**Comment by sailoog** [comment]
oops, ok, sorry. We are implementing a NMEA 0183 sentence builder from SK data on OpenPlotter to generate custom XDR, etc. I suppose we can parse the entire data model at this moment but implementing this feature would be great.
