### ISSUE TITLE
Can't Add iKommunicate as Signalk Web Socket Connection

### ISSUE THREAD

**Issue by mmchruser** [SignalK/signalk-server-node#1005]
I can't successfully add iKommunicate gateway as a WebSocket "Connection" on a SignalK Server. It only results in 501 error. I can connect web socket using chrome web socket tool no issue.

But adding iKommunicate gateway as a WebSocket "Connection" on the SignalK Server results in 501 error.

/home/pi/.signalk/settings.json
...
{
"pipeElements": [
{
"type": "providers/simple",
"options": {
"logging": true,
"type": "SignalK",
"subOptions": {
"type": "ws",
"host": "192.168.1.98",
"port": "80",
"providerId": "53353100-4148-484e-3230-383039353035",
"useDiscovery": false
},
"providerId": "53353100-4148-484e-3230-383039353035"
}
}
],
"id": "53353100-4148-484e-3230-383039353035",
"enabled": true
}

![image](https://user-images.githubusercontent.com/31142190/77672969-cadb8780-6f46-11ea-8dbb-fae5dcd96eb5.png)

Unexpected server response: 501

**Comment by tkurki** [comment]
The error message is from a Varnish http server/reverse proxy. Are you sure you have the correct ip address?

**Comment by mmchruser** [comment]
![image](https://user-images.githubusercontent.com/31142190/77680753-a0db9280-6f51-11ea-85a9-e718bdaaa77f.png)

![image](https://user-images.githubusercontent.com/31142190/77680809-b3ee6280-6f51-11ea-9a4b-8de30a8f45ce.png)

**Comment by mmchruser** [comment]
For sure IP is right of the iKommunicate server...192.168.1.98

**Comment by tkurki** [comment]
Oh right, I got served an error message from Github for the screenshot! I don’t have an iK available right now to be able to test.

**Comment by mmchruser** [comment]
You want to connect to my network?

**Comment by sbender9** [comment]
This is not working because the iKommunicate does not conform to the SignalK subscription specs. It does not support `subscription=none`. 

This was broke in the node server when I upgraded to use the new signalk-is-client library. 

I will work to fix this,  it probably won’t be unit next week. 

I’m the meantime you can use node server version 1.20.0.

**Comment by mmchruser** [comment]
Amazing.  I will try it now.  I have been messing with this stuff for a few years now and just finally to get serious.  The response from you guys is tremendous and inspiring.  

So does that mean everyone who has an iKommunicate will be broken?  Is there anyway to adjust the subscription?  Thank you!

**Comment by sbender9** [comment]
Yeah, will break anyone connecting to an iKommunicate.

I don't think there's an easy way to adjust the subscription, but I have not yet dug deep enough into the client library yet...

**Comment by mmchruser** [comment]
I can confirm 1.20.0 it is working.  Instrument panel now is not but I wasn't planning on using it anyway!  Thank you!

**Comment by sbender9** [comment]
Too much work to try to make signalk-js-client work with this, so I made a small simple plugin to do it: https://github.com/sbender9/signalk-ikommunicate-connector

Should show up on the App Store shortly.

Remove your existing connection and install and configure this plugin.

**Comment by mmchruser** [comment]
Roger that, I am sure someone will find it useful besides me!  I can't believe more people do not have iK and alerting of the same issue.

**Comment by mmchruser** [comment]
Showed in the store but doesnt seem to work.

![image](https://user-images.githubusercontent.com/31142190/77711194-8a532c80-6f8d-11ea-9e04-584502bc5e7e.png)

**Comment by sbender9** [comment]
Never seen that before. On the boat and don’t have an iKomminicate to test with. Will be home tomorrow and will grab it.

**Comment by mmchruser** [comment]
When I tried it the first time, I had my previously attempted Connection still in the SignalK connections.  I removed it and now I am getting the below.  Possibly a "duplicate" conflict?  

No data showing coming in but it says connected now.

![image](https://user-images.githubusercontent.com/31142190/77717546-035a8000-6f9e-11ea-94b4-d58c8081f2fe.png)

**Comment by mmchruser** [comment]
Looks like iK server had crashed when I had taken above screen shot.  Now its back to this and its refreshing like crazy.  I think its crasing the iK gateway.

![image](https://user-images.githubusercontent.com/31142190/77718366-fc347180-6f9f-11ea-9e2f-31553dc7cacd.png)

**Comment by mmchruser** [comment]
Now I am trying a work around.  Connect to iKommunicate Gateway via node-red / websocket and then send the data to the SignalK server.  Connecting the iKommunicate Gateway websocket was easy but now I am trying to figure out how to forward all the data to the SignalK server.

iKommunicate Gateway (192.168.1.98)
SignalK Server - Node-Red (192.168.1.170) 

<img width="881" alt="image" src="https://user-images.githubusercontent.com/31142190/78509142-b9f9f580-7740-11ea-8537-0ed110a98f26.png">

**Comment by mmchruser** [comment]
Thank you everyone for trying.  The work-around worked.  I used node-red to connect to the iK signalK gateway and then sent it to the SignalK server with a "signalk-send-pathvalue node".  

Let me know if anyone needs help with it.  I hired a great guy that knew nothing about SignalK but knows Node-Red and he got it done!  Thanks to https://github.com/alexmed

**Comment by mmchruser** [comment]
I can't believe I am the only one connecting an iK to SignalK!
