### ISSUE TITLE
Problem installing signalk-derived-data v 1.24.3 from Signal K Appstore/Available

### ISSUE THREAD

**Issue by edefalque** [SignalK/signalk-server-node#1006]
When installing signalk-derived-data v 1.24.3 from Signal K Appstore/Available, it does not show in Appstore/Installed.  Derived-data plugin config shows title "Derived Data with Polars, package name @ib236/signalk-derived-data, which is probably a deprecated plugin.
When activated, Data Browser shows environment.wind.angleTrue (not in Signal K keys specs) instead of environment.wind.angleTrueWater.

**Comment by tkurki** [comment]
Sounds like you have indeed @ib236/signalk-derived-data installed. It has been deprecated for quite a while now. You should purge your $HOME/.signalk/node_modules, make sure it is no longer listed in $HOME/.signalk/package.json, run `npm install` in $HOME/.signalk and restart the server.

The newly installed plugins should show up like this under Appstore/Installed:

![image](https://user-images.githubusercontent.com/1049678/77769687-d5804480-704c-11ea-8a4a-a79767771448.png)

`signalk-derived-data`  installs fine on my machine.

**Comment by edefalque** [comment]
Many thanks Teppo. Purged and re-installed Signal K.  New signalk-derived-data installs fine now.
