### ISSUE TITLE
Frequent crashes of node process with data interruptions

### ISSUE THREAD

**Issue by BenPanbo** [SignalK/signalk-server-node#1017]
I'm seeing an issue with frequent crashing of the Node process when collecting NMEA 2000 raw data from a YDWG-02 via a TCP stream. 

I'm not seeing any errors logged, but I can watch the process recycle about every 30 seconds with data disruptions each time. I've tried many different things to reduce the issues. If I switch to an 0183 stream things seem to work better but I also lose a good bit of data like additional instances of temp sensors, etc. 

I do have a fairly large, heterogeneous N2K network with about 40 devices. The network averages around 20% bus utilization. As part of that I do seem to see pretty high CPU consumption of the node process with it frequently pegging one of the four cores in the RPi-3-B+.

I'd love to help figure out what message or messages are causing an issue, as that's what I'm assuming is probably happening but I'm not sure where to start. 

Ben

**Comment by tkurki** [comment]
Definitely interesting. 

Nothing in syslog? Like a poison pgn that comes every now and then and crashes the server. Or a node crash report.

Could you log your data for Scott and/or me to replay? Either using the SK server’s logging or from command line `nc ip port >filename.data`. Or if you are able to arrange remote access.

Easiest would be to continue in Signal K Slack, but email is also good for private comms.

**Comment by BenPanbo** [comment]
[skserver-raw_2020-04-13T11.log](https://github.com/SignalK/signalk-server-node/files/4470455/skserver-raw_2020-04-13T11.log)
I joined the Slack support channel and added some detail there. Here's the captured data stream, though I wonder if this is complete since it's possible the "poison" message is killing the proc before it logs the message?

**Comment by tkurki** [comment]
Fixed in https://github.com/canboat/canboatjs/pull/111
