### ISSUE TITLE
VHF call sign to Vessel data

### ISSUE THREAD

**Issue by KEGustafsson** [SignalK/signalk-server-node#1018]
Do you see feasible to add VHF call sign information to Vessel data, as a configurable parameter?
I did this modification to myself and now e.g. aisreporter can send VHF call sign (callsignVhf) to UDP endpoints.

**Comment by tkurki** [comment]
You mean add to the admin UI? Sure!

**Comment by KEGustafsson** [comment]
Jep, to admin UI VesselConfiguration.js and respectively to serverroutes.js
