### ISSUE TITLE
SignalK doesn't install with NPM

### ISSUE THREAD

**Issue by aiacopini** [SignalK/signalk-server-node#1024]
Hi Guys,
we're trying to explore SignalK.
After cloning via Git, we go into /signalk-server-node/packages/streams/ and /signalk-server-node/packages/server-admin-ui for npm link.

Later, we launch npm install and we got this
root@enkeli-VirtualBox-Dev:/home/enkeli/Desktop/SignalK/signalk-server-node# npm install

> mdns@2.5.1 install /home/enkeli/Desktop/SignalK/signalk-server-node/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/home/enkeli/Desktop/SignalK/signalk-server-node/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:10: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
          ^~~~~~~~~~
compilation terminated.
dns_sd_bindings.target.mk:168: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/home/enkeli/Desktop/SignalK/signalk-server-node/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.3.0-46-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/enkeli/Desktop/SignalK/signalk-server-node/node_modules/mdns
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mdns@2.5.1 (node_modules/mdns):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mdns@2.5.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

Any idea?

**Comment by tkurki** [comment]
This is not a serious error and to be expected, the npm messages are all WARN and it says it is SKIPPING OPTIONAL DEPENDENCY, not that the installation was a failure.

**Comment by tkurki** [comment]
reopen if needed
