### ISSUE TITLE
iKonvert not connecting

### ISSUE THREAD

**Issue by Boatly** [SignalK/signalk-server-node#1045]
SignalK server versions 1.29.0 & 1.30.0

Digital Yacht iKonvert is connected to port '/dev/ttyUSB1' on my RaspberryPi.

I don't receive any data and the N2K LED is not illuminated on the iKonvert, although it briefly flashed when I restart the SignalK server.

Server log is as follows:

May 19 21:36:45 ikonvertOut
May 19 21:36:45 signalk-server running at 0.0.0.0:[object Object]
May 19 21:36:46 (node:1079) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'undefined' of undefined at iKonvertStream._transform (/usr/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/ikonvert.js:187:37) at iKonvertStream.Transform._read (_stream_transform.js:191:10) at iKonvertStream.Transform._write (_stream_transform.js:179:12) at doWrite (_stream_writable.js:442:12) at writeOrBuffer (_stream_writable.js:426:5) at iKonvertStream.Writable.write (_stream_writable.js:317:11) at Log.ondata (_stream_readable.js:695:22) at Log.emit (events.js:310:20) at addChunk (_stream_readable.js:286:12) at readableAddChunk (_stream_readable.js:268:9) at Log.Readable.push (_stream_readable.js:209:10) at Log.Transform.push (_stream_transform.js:152:32) at Log._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/log.js:46:8) at Log.Transform._read (_stream_transform.js:191:10) at Log.Transform._write (_stream_transform.js:179:12) at doWrite (_stream_writable.js:442:12)
May 19 21:36:46 (node:1079) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
May 19 21:36:46 (node:1079) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sbender9** [comment]
Can you come to the #support channel on Slack when you have some time to troubleshoot this? (http://slack-invite.signalk.org/)

**Comment by sbender9** [comment]
In the mean time, you can revert to the previous version of canboatjs:

```
cd /usr/lib/node_modules/signalk-server
sudo npm install @canboat/canboatjs@1.12.2
```

**Comment by Boatly** [comment]
Yes, I'll report it on Slack.  

Reverting to the previous version of canboatjs got it working again, thanks very much.

**Comment by sbender9** [comment]
I'm keeping this open until I find the issue...

**Comment by sbender9** [comment]
ok this is fixed. Can you please try it out.

```
cd /usr/lib/node_modules/signalk-server
sudo npm install @canboat/canboatjs@1.13.1
```

**Comment by Boatly** [comment]
I can confirm it's working perfectly now.  

Thanks very much for the fix and apologies for the delay in responding .... I actually managed to get out sailing for a few days.
