### ISSUE TITLE
Installation produces a lot of warnings, make and build errors

### ISSUE THREAD

**Issue by mcdonaldajr** [SignalK/signalk-server-node#1051]
Did a fresh install of Rasbian 2020-02-13-rasbian-buster-full.img
sudo apt-get update
sudo apt dist-upgrade
sudo apt update
sudo apt install nodejs npm
sudo npm install -g npm@latest

sudo npm install -g --unsafe-perm signalk-server

[signal k install log.txt](https://github.com/SignalK/signalk-server-node/files/4692259/signal.k.install.log.txt)

**Comment by sbender9** [comment]
Sadly, this is to be expected. It's all warnings and an issue with an optional dependency.
