### ISSUE TITLE
Missing output option in NMEA0183 TCP client

### ISSUE THREAD

**Issue by marcelrv** [SignalK/signalk-server-node#1054]
I'm trying to configure a TCP client (which connects to GPS/chartplotter) to send AIS messages to the client? (to phase out kplex from the setup)

When configuring a serial connection there is the possibility to  specify 'Output Events' and use the  nmea0183-to-nmea0183 plugin, but this appears not be available for tcp client.

Hence the TCP client seems only possible to allow input and can't be used for output

**Comment by tkurki** [comment]
It would be fairly straightforward to add it. You did such a good job with the checksum, feel like asding this also? As you said serial has this and can be used as an example.

**Comment by marcelrv** [comment]
yes, indeed I already did. and indeed seems to be working fine.
