### ISSUE TITLE
signalk-websocket-provider: "Failed to start: undefined"

### ISSUE THREAD

**Issue by jwillmer** [SignalK/signalk-server-node#1094]
I get this message in the Dashboard:

![image](https://user-images.githubusercontent.com/1503577/89394627-96ee4b00-d70c-11ea-9a2a-2dc7c5a253b8.png)

But the logs do not show any issues. I also believe that most of the API calls are not working anymore and that this message might be the reason. Could someone explain what this error message means and how I can fix it?

**Comment by tkurki** [comment]
Can you post your settings.json? Usually $HOME/.signalk/settings.json

>believe that most of the API calls are not working 

What did you mean with this?

**Comment by tkurki** [comment]
Probably this - https://www.npmjs.com/package/signalk-websocket-provider

Do you need it? If not please remove it (Appstore => Installed).

**Comment by jwillmer** [comment]
Yes, I found that this plugin seams to be the problem. But I don't see it installed in "AppStore => Installed". Any way to remove it manually?

**Comment by jwillmer** [comment]
I removed `signalk-websocket-provider` from `package.json` and deleted the `signalk-websocket-provider`  folder from node_modules. That seams to do the trick. Will test the app again but at least the error msg is gone.
