### ISSUE TITLE
server does not publish uuid to 'self' property

### ISSUE THREAD

**Issue by ph1l** [SignalK/signalk-server-node#111]
as specified here: https://github.com/SignalK/specification/blob/master/schemas/signalk.json#L12, a signalk server shoud publish the self propery containing the uuid of the vessel on which the server is running.

**Comment by tkurki** [comment]
It is actually not required by the schema, but I agree it would be good idea to implement that *and* make it required in the schema.

https://github.com/SignalK/specification/blob/master/schemas/signalk.json#L7-L12

**Comment by sumps** [comment]
So the restAPI URL would be....

http://hostname/signalk/v1/api/self

Which should be responded to with...

// 20161031140214
// http://192.168.0.80/signalk/v1/api/self

{
  "urn:mrn:imo:mmsi:234567890"
}

**Comment by tkurki** [comment]
No, the response is `"urn:mrn:imo:mmsi:234567890"`.

```
{
"urn:mrn:imo:mmsi:234567890"
}'
```
is not valid JSON.

**Comment by tkurki** [comment]
Fixed by 3a437edeea148ba0248e532dfb029d6a869b5c5f and https://github.com/SignalK/specification/commit/a97d19ea05f695b2310798702e070ccd5638ce41.
