### ISSUE TITLE
hostname not correct in http://raspberrypi.domain:3000/signalk

### ISSUE THREAD

**Issue by ph1l** [SignalK/signalk-server-node#112]
Expected Output: server should return FQDN in /signalk response: `raspberrypi.domain`

Actual Output: server returns short hostname: `raspberrypi`

the server is correctly configured and the output of `hostname -f` is `raspberrypi.domain`

**Comment by tkurki** [comment]
I am not aware of anything else than invoking `hostname -f` to retrieve this. Do you have any better ideas?

**Comment by ph1l** [comment]
how about getting it from the client http request header 'Hostname'.

This will be the hostname that the client used to connect, so guaranteed that the client can further connect to api and stream endpoints.
--

**Comment by tkurki** [comment]
How does the client connect when it does not get a correct hostname from
the mdns?

This happens when server starts, client plays no role here.

maanantai 7. marraskuuta 2016 Philip Freeman <notifications@github.com>
kirjoitti:

> how about getting it from the client http request header 'Hostname'.
>
> This will be the hostname that the client used to connect, so guaranteed
> that the client can further connect to api and stream endpoints.
> --
> Sent from my Blackphone with K-9 Mail. Please excuse my brevity.
>
> On November 7, 2016 9:08:27 AM PST, Teppo Kurki <notifications@github.com

**Comment by ph1l** [comment]
mdns is working fine..

**Comment by tkurki** [comment]
Oops sorry, my mistake. Remembered this was about mdns advertisement, but
so it is /signalk.

maanantai 7. marraskuuta 2016 Philip Freeman <notifications@github.com>
kirjoitti:

**Comment by ph1l** [comment]
Reference Discovery Document: http://signalk.org/specification/master/connection.html

I am referring to `Connection Establishment`, which is post mdns..

```
* Make a GET call to (eg http://10.1.1.40:8080/signalk from above) 
* And get the endpoints json 
```

**Comment by ph1l** [comment]
The endpoints json does not contain valid urls in my case. this rest response should use the Hostname from HTTP request headers..

**Comment by ph1l** [comment]
```
$ curl --verbose http://signalk.local.:3000/signalk | json_pp
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.122.170...
* Connected to signalk.local (192.168.122.170) port 3000 (#0)
> GET /signalk HTTP/1.1
> User-Agent: curl/7.38.0
> Host: signalk.local:3000
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Content-Type: application/json; charset=utf-8
< Content-Length: 147
< ETag: W/"93-LDoVNDvVriZMO5deDdUF2Q"
< Date: Mon, 07 Nov 2016 21:36:43 GMT
< Connection: keep-alive
< 
{ [data not shown]
100   147  100   147    0     0  15294      0 --:--:-- --:--:-- --:--:-- 16333
* Connection #0 to host signalk.local left intact
{
   "endpoints" : {
      "v1" : {
         "signalk-http" : "http://signalk:3000/signalk/v1/api/",
         "version" : "1.alpha1",
         "signalk-ws" : "ws://signalk:3000/signalk/v1/stream"
      }
   }
}
```

**Comment by tkurki** [comment]
For the time being you can override the OS hostname in the settings file with top level `hostname` property (a71de364878f4b9c5f7ec5be3bd7e88b2eef9f39).

**Comment by ph1l** [comment]
That works, thanks!
