### ISSUE TITLE
Missing dependency in the node server?

### ISSUE THREAD

**Issue by ndelaet** [SignalK/signalk-server-node#167]
Hi,

just updated the SignalK Server, and got the following messages: 

> npm WARN request-promise@4.2.0 requires a peer of request@^2.34 but none was installed.
> npm WARN request-promise-core@1.1.1 requires a peer of request@^2.34 but none was installed. 

something else to update  before updating the SK server?

**Comment by tkurki** [comment]
Fixed by a740d10c04558a374cb424a07ad27353d6927ae1.

This was not a real problem, as request-promise is used only in the tests and everything was actually working despite the warning.

Anyway, thanks for pointing this out.
