### ISSUE TITLE
Logging for non-provider data

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#221]
Current provider setup allows you to add logging element to a provider pipe. Depending on the exact configuration you can log either raw data (not yet in SK format) or after conversion to SK format.

However data produced by plugins does not flow through a provider pipe and thus logging is not possible.

**Comment by tkurki** [comment]
How about making it possible to create provider pipes for plugins, identified by plugin id? 

Currently plugins are supposed to call `app.handleMessage` to insert deltas. What delta from plugins was inserted into the beginning of a pipe, if there is a matching (provider id === plugin id) pipe?

This would allow we to use same logging configuration and possibly other pipe elements.

@sbender9 your thoughts?

**Comment by sbender9** [comment]
I like it. Maybe allow to configure for "all" plugins, so we don't need to configure for each one unless needed.

**Comment by tkurki** [comment]
Fixed quite some time ago.
