### ISSUE TITLE
Charts with special characters does not load

### ISSUE THREAD

**Issue by joabakk** [SignalK/signalk-server-node#240]
So I have tested with different charts, and there seems to be a problem adding charts with special characters such as ö,ä,å,æ,ø in the names. I use freeboard-installer, with the ISO-8859-1 setting. The names seem ok in the resources/charts call, such as
```
{"1111_Översikt_Svenska_Sjökort_(2000)":{"identifier":"1111_Översikt_Svenska_Sjökort_(2000)","name":"Översikt Svenska Sjökort","description":"Översikt Svenska Sjökort","tilemapUrl":"/mapcache/1111_Översikt_Svenska_Sjökort_(2000)","scale":4000000}
```
And they appear to be named correctly in freeboard-sk listings, but do not appear when they should (right zoom level, activated etc)

Any charts without these characters are ok.

Is it possible there is an issue with ISO-8859-1 characters in general?

**Comment by tkurki** [comment]
Could you share with me privately the files that are giving you trouble?

**Comment by joabakk** [comment]
Just sent one in email. Thanks for looking into it.

**Comment by tkurki** [comment]
I don't think this is an issue with the server.

The zip file that you provided had ö character in wrong encoding (not utf-8, which the xml declaration states).

On my machine freeboard-sk is able to show the data on intermediate zoom levels, which is actually consistent with tilemapresource.xml having only zoom levels 4-8. If you zoom closer you only get the hardcoded OpenStreetMap base map.

I had a look at the original KAP file you shared with gdal2tiles.py and that produced tiles with more detailed tiles.

All in all I'd say it is a conversion issue.

**Comment by joabakk** [comment]
Ok thanks for looking into it Teppo
