### ISSUE TITLE
MBTiles handling

### ISSUE THREAD

**Issue by joabakk** [SignalK/signalk-server-node#253]
The code does not seem to handle mbtiles. Does anyonehave a working node server with mbtiles charts?

What seems to happen is that the server looks for `/charts/<name>.mbtiles/%7Bz%7D/%7Bx%7D/%7By%7D/tilemapresource.xml` which does not exist. First of all, the map folder should probably be `public/charts/<name>/`, and it should not look for an xml file?

Also, z,x and y are not defined in this function: https://github.com/SignalK/signalk-server-node/blob/master/lib/interfaces/charts.js#L147-L176

**Comment by tkurki** [comment]
Tuktuk plotter in the app store and https://github.com/vokkim/rannikkokartat-mbtiles

**Comment by tkurki** [comment]
When you say the server looks you probably mean that freeboard requests, as the path looks like a http request path.

**Comment by tkurki** [comment]
The function you linked returns info about a chart and creates a chart provider that will serve the tiles, why would it need z x y?

**Comment by joabakk** [comment]
You are right, it is freeboard-sk that looks for it, but z,x and y are used in https://github.com/SignalK/signalk-server-node/blob/master/lib/interfaces/charts.js#L169 without definition.

**Comment by joabakk** [comment]
Ok I understand more of the flow now. I will propose some more documentation on charts when I have more figured out.
