### ISSUE TITLE
Calculated data.

### ISSUE THREAD

**Issue by ieb** [SignalK/signalk-server-node#256]
Is it possible to use a Server Plugin to calculate standard schema values from existing data and inject that data back into the SignalK model.

eg, I have awa, aws, stw and leeway. I can calculate tws, twa and would like to inject those new values back into SingalK so that other plugins can use the data.  

Perhaps a Server Plugin, which is convenient with the Bacon mechanism, is the wrong place to do this and I should be using something else. At the moment I do all the calculations in my Server plugin but don't share the results back.

**Comment by fabdrol** [comment]
You could write a server plugin or a provider. Th upside of a plugin is that you can enable a config page for it

**Comment by joabakk** [comment]
Please contribute wit pull requests to https://github.com/sbender9/signalk-derived-data.

**Comment by tkurki** [comment]
Scott's plugin is the way forward, let's continue the discussion there.

**Comment by ieb** [comment]
https://github.com/sbender9/signalk-derived-data is perfect. Thanks for the pointer will contribute there.
