### ISSUE TITLE
Pi setup script should not run server as root

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#259]
I haven't used the script myself, but @sbender9 reported that the Pi setup script makes the server run as root.

Fix should be easy, see https://github.com/tkurki/marinepi-provisioning/blob/master/roles/node-app/templates/node_app_systemd_script.j2#L8.

**Comment by tkurki** [comment]
@joabakk could you take a shot at this?

**Comment by joabakk** [comment]
I will, thanks for the feedback
