### ISSUE TITLE
I2C Wind sensor??

### ISSUE THREAD

**Issue by elalemanyo** [SignalK/signalk-server-node#263]
Hi,
Any suggestion for a good but not very expensive I2C Wind sensor?
I am trying to use Signal K to get the speed and direction of the wind on a cheap way.

Thanks!

**Comment by tkurki** [comment]
I know that people have used Peet Bros anemometer:
- http://www.peetbros.com/shop/custom.aspx?recid=14
- https://mechinations.net/2014/12/27/building-a-nmea-0183-wind-instrument/
- https://github.com/rob42/FreeboardPLC_v1_2/blob/master/Wind.cpp

You should ask the same question on the SK mailing list/google group https://groups.google.com/forum/#!forum/signalk or on our Slack forum https://signalk-dev.slack.com/, you would probably contact more like minded people there.
