### ISSUE TITLE
SyntaxError running bin/nmea-from-file

### ISSUE THREAD

**Issue by gregology** [SignalK/signalk-server-node#272]
Hey Team, I'm getting this error when running `bin/nmea-from-file` on a Raspberry Pi 3.

```
pi@shipscomputer:~/signalk-server-node $ bin/nmea-from-file
/home/pi/signalk-server-node/lib/index.js:61
    let { result, footer } = page(__dirname + "/index.html", "</ul>");
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/signalk-server-node/bin/signalk-server:19:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

I feel like I'm doing something obviously wrong. I followed the [Raspberry Pi Installation Guide](https://github.com/SignalK/signalk-server-node/blob/master/raspberry_pi_installation.md) and hit this issue when I ran `bin/nmea-from-file`. I tried creating a config file for our vessel with `./rpi-setup.sh` but ran into the same error when I ran `bin/nmea-from-file`. Any ideas on what I'm doing wrong or other trouble shooting suggestions?

**Comment by tkurki** [comment]
What version of node do you have?

**Comment by gregology** [comment]
@tkurki, I just left the boat :) I'll reinstall on a local pi and see if I can reproduce the issue. And I'll get back to you re node version in a week or two. Thanks mate!

**Comment by gregology** [comment]
Back on the boat @tkurki :)

```
$ node --version
v4.3.2
$ nodejs --version
v8.4.0
$ npm --version
2.14.12
```

**Comment by tkurki** [comment]
Signal K Node server requires minimim Node version 6, so that the command `node` starts it. 

That looks strange: you have both an ancient `node` and the latest node as `nodejs`, and npm is ancient as well.

Sorry, I probably won't be much help, as I have no idea how you ended up like that nor exact steps  to fix it. Can you start over with a new RPi installation?

**Comment by gregology** [comment]
Yeah, I'm not sure what I had done. I'll start again :+1: thanks for your help mate
