### ISSUE TITLE
Mapping/enrichment layer

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#28]
One should be able to add mapping/enrichment/correction layer to the server.

It should be easy to add logic such as sample averaging (to reduce noise), device calibration, or analysis (computing TWS/TWA gives AWS/AWA/Speed/Heading).

Most implementations do all of these calculations per display.  The problem with that is that you can have different configurations per display, so one display might show depth from waterline while another shows depth from maximum draft.  Averaging and calculations are also done per display.  Higher end systems (aimed primarily at race sailboats) often do have an aggregator for this reason.

**Comment by fabdrol** [comment]
It would be very nice if we could just "pipe" something like this between multiplexer and the interfaces (e.g. make multiplexer a transform stream and each interface a writable stream)

**Comment by tkurki** [comment]
If the enriched data is to be available via rest api it needs to go back to multiplexer as well.

FRP provides nice toolbag for implementing the logic.

**Comment by tkurki** [comment]
Closing as too vague. This will get implemented with a specific need I think.
