### ISSUE TITLE
Plugin type: "number" will not accept 0

### ISSUE THREAD

**Issue by joabakk** [SignalK/signalk-server-node#281]
I get an error message when I try to enter `0` in a plugin schema field with `type: "number"` The playground on https://mozilla-services.github.io/react-jsonschema-form/ does not seem to have an issue with 0's. Is there something specific in our implementation of this module?

**Comment by tkurki** [comment]
I have seen that before, but can not reproduce right now. Instructions?

I updated the plugin config ui deps anyway, if you can reproduce please try with that latest deps as well: #283

**Comment by joabakk** [comment]
I get an error from time to time, but apparently, I am able to wiggle out of it bu removing the entry and writing it back. The updated deps did not do any harm. Thanks for looking into a vague issue...
