### ISSUE TITLE
Serve bower files by default

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#29]

**Comment by fabdrol** [comment]
I still don't like this solution, it's ugly and hackish. If you do feel strongly about serving consumer files along with the server, I'd propose:
- Package a special server that sandboxes each component (powered by bower), based on a special flag in bower.json
- Make this user-configurable

**Comment by tkurki** [comment]
Ease of use over perceived ugliness.

It is now user-configurable, not the default. 

I was willing to entertain this being optional behavior until the first time an end user reports that hey things are not working. This happened yesterday on the list, so it is time change the default.

**Comment by tkurki** [comment]
This feature enables you to serve the contents of the bower_components directory from the root and unsed /bower_components so that what you install with bower is available via http.

@fabdrol I don't understand what you mean by sandboxing. What would it do eg. what should be limited?

**Comment by tkurki** [comment]
Done.
