### ISSUE TITLE
securityStrategy.verifyWS is not applied for some connections

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#290]
Cases not covered
- no subscribe parameter
- subscribe=none
- subscribe=self

https://github.com/SignalK/signalk-server-node/blob/master/lib/interfaces/ws.js#L105-L117

The security check should probably wrap the `onChange` function.

**Comment by tkurki** [comment]
Ping @sbender9

**Comment by sbender9** [comment]
On it...

**Comment by tkurki** [comment]
Closed in #292
