### ISSUE TITLE
Mbtiles charts with no name do not work

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#300]

**Comment by tkurki** [comment]
@netAction do you happen to have an example file that I could replicate this problem with?

**Comment by netAction** [comment]
Built using https://github.com/mapbox/mbutil from a directory with just directories of PNG tiles, no metadata file.

    ./mb-util --scheme=xyz --image_format=png   ./tiles/ naked-testchart.mbtiles

[naked-testchart.mbtiles.zip](https://github.com/SignalK/signalk-server-node/files/1360796/naked-testchart.mbtiles.zip)

**Comment by netAction** [comment]
Confirm it works (y)
