### ISSUE TITLE
Plugin updates may crash server

### ISSUE THREAD

**Issue by joabakk** [SignalK/signalk-server-node#319]
This is related to #268, but specific for plugin updates. If a new field is added to the plugin-schema, and the plugin has been activated before the update, the server crashes. It finds the existing `plugin-config-data/[plugin-name].json`, but the new field is missing. 
Ideally, it should 
A - not crash
B - honour the info existing in the old config file (or at least make a backup)

**Comment by tkurki** [comment]
See #87. This has been open so long that seems to me that this is not a huge problem.
