### ISSUE TITLE
Data from defaults.json has no source.

### ISSUE THREAD

**Issue by sbender9** [SignalK/signalk-server-node#328]
Data from defaults currently show up with `$source` as `undefined`. We should make it be `defaults` so that it is clear where the data came from.

**Comment by sbender9** [comment]
Not sure if this belongs in specification since this is partially handled there?

**Comment by tkurki** [comment]
Defaults is just a way to prime the full model in this server. You can add sources there the way you want it, it is used verbatim.

If/when there is a UI or an app to create defaults then that should create source data.
