### ISSUE TITLE
Tree Model for Updated Data

### ISSUE THREAD

**Issue by zapfware** [SignalK/signalk-server-node#34]
To make parsing of updated data easier and to have only model to parse, it would be nice to get the updated data also in the tree model. 

Further a nice to have feature would be to receive the whole tree on connection.
This solves the problem to open a connection to the "full tree URL", disconnecting after receiving a full tree and opening a connection to the "update tree URL" to receive only the updates.

**Comment by tkurki** [comment]
I think the best pattern here would be to retrieve the tree via http and then start listening for delta updates. It would be pretty easy to send optionally the whole tree upon connection, but that should go into http://signalk.org/developers/apis_and_conventions.html as part of the specification.

If I recall correctly you worked around this. 

Closing for now, open an issue under https://github.com/SignalK/specification if you think this is still worth the effort.
