### ISSUE TITLE
switched labels on admin interface?

### ISSUE THREAD

**Issue by sailoog** [SignalK/signalk-server-node#367]
Are "Ignored if MMSI is set" and "Leave blank if there is no mmsi" labels in the right place?
![captura de 2017-12-29 14-25-25](https://user-images.githubusercontent.com/8145560/34438260-b51a91c8-eca5-11e7-8ce1-3db7a3352f62.png)

**Comment by tkurki** [comment]
Lol, this was the token error that checks if anybody is actually using the app & being awake!

In reality I noticed this but forgot to fix - thanks for the reminder! 

Fixed in @signalk/server-admin@0.0.3.
