### ISSUE TITLE
Installation failure with no dns_sd.h present

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#40]
Raspberry pi 2
Debian mini with lxde, kernel 3.18.8-v7+
node v 0.12.0
bower v1.4.1

3280 error Linux 3.18.8-v7+
3281 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
3282 error node v0.12.0
3283 error npm  v2.5.1
3284 error code ELIFECYCLE
3285 error mdns@2.2.8 install: `node-gyp rebuild`
3285 error Exit status 1
3286 error Failed at the mdns@2.2.8 install script 'node-gyp rebuild'.

**Comment by tkurki** [comment]
cc @manuprendlair

**Comment by manuprendlair** [comment]
Hello,

To pass this install error I installed this:
sudo apt-get install libavahi-compat-libdnssd-dev

and the install seem to work :

opencpn@blueocean-nav:~/signalk/signalk-server-node$ npm install
npm WARN package.json express-namespace@0.1.1 No repository field.
npm WARN package.json n2k-signalk@0.0.0 No repository field.
 
> mdns@2.2.8 install /home/opencpn/signalk/signalk-server-node/node_modules/mdns
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/opencpn/signalk/signalk-server-node/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_browse.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_enumerate_domains.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_get_addr_info.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_process_result.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_sock_fd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_register.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_resolve.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/mdns_utils.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/network_interface.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/socket_watcher.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_create.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_set_value.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_get_length.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_buffer_to_object.o
  SOLINK_MODULE(target) Release/obj.target/dns_sd_bindings.node
  SOLINK_MODULE(target) Release/obj.target/dns_sd_bindings.node: Finished
  COPY Release/dns_sd_bindings.node
make: Leaving directory '/home/opencpn/signalk/signalk-server-node/node_modules/mdns/build'
n2k-signalk@0.0.0 node_modules/n2k-signalk
├── nomnom@1.6.2 (colors@0.5.1, underscore@1.4.4)
├── JSONStream@0.7.4 (jsonparse@0.0.5)
└── signalk-schema@0.0.1 (tv4@1.1.9, chai@1.9.2)

nmea0183-signalk@0.2.4 node_modules/nmea0183-signalk
├── signalk-multiplexer@0.1.10
└── ggencoder@0.1.6 (async@0.9.0, jison@0.4.15)

mdns@2.2.8 node_modules/mdns
├── bindings@1.2.1
└── nan@1.5.3



Best regards.

**Comment by manuprendlair** [comment]
Hello,

To pass this install error I installed this:
sudo apt-get install libavahi-compat-libdnssd-dev

and the install seem to work :

opencpn@blueocean-nav:~/signalk/signalk-server-node$ npm install
npm WARN package.json express-namespace@0.1.1 No repository field.
npm WARN package.json n2k-signalk@0.0.0 No repository field.
 
> mdns@2.2.8 install /home/opencpn/signalk/signalk-server-node/node_modules/mdns
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/opencpn/signalk/signalk-server-node/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_browse.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_enumerate_domains.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_get_addr_info.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_process_result.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_sock_fd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_register.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_resolve.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/mdns_utils.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/network_interface.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/socket_watcher.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_create.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_set_value.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_get_length.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_buffer_to_object.o
  SOLINK_MODULE(target) Release/obj.target/dns_sd_bindings.node
  SOLINK_MODULE(target) Release/obj.target/dns_sd_bindings.node: Finished
  COPY Release/dns_sd_bindings.node
make: Leaving directory '/home/opencpn/signalk/signalk-server-node/node_modules/mdns/build'
n2k-signalk@0.0.0 node_modules/n2k-signalk
├── nomnom@1.6.2 (colors@0.5.1, underscore@1.4.4)
├── JSONStream@0.7.4 (jsonparse@0.0.5)
└── signalk-schema@0.0.1 (tv4@1.1.9, chai@1.9.2)

nmea0183-signalk@0.2.4 node_modules/nmea0183-signalk
├── signalk-multiplexer@0.1.10
└── ggencoder@0.1.6 (async@0.9.0, jison@0.4.15)

mdns@2.2.8 node_modules/mdns
├── bindings@1.2.1
└── nan@1.5.3



Best regards.

**Comment by manuprendlair** [comment]
Hello,

To pass this install error I installed this:
sudo apt-get install libavahi-compat-libdnssd-dev

and the install seem to work :

opencpn@blueocean-nav:~/signalk/signalk-server-node$ npm install
npm WARN package.json express-namespace@0.1.1 No repository field.
npm WARN package.json n2k-signalk@0.0.0 No repository field.
 
> mdns@2.2.8 install /home/opencpn/signalk/signalk-server-node/node_modules/mdns
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/opencpn/signalk/signalk-server-node/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_browse.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_enumerate_domains.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_get_addr_info.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_process_result.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_sock_fd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_register.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_resolve.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/mdns_utils.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/network_interface.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/socket_watcher.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_create.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_set_value.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_get_length.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_buffer_to_object.o
  SOLINK_MODULE(target) Release/obj.target/dns_sd_bindings.node
  SOLINK_MODULE(target) Release/obj.target/dns_sd_bindings.node: Finished
  COPY Release/dns_sd_bindings.node
make: Leaving directory '/home/opencpn/signalk/signalk-server-node/node_modules/mdns/build'
n2k-signalk@0.0.0 node_modules/n2k-signalk
├── nomnom@1.6.2 (colors@0.5.1, underscore@1.4.4)
├── JSONStream@0.7.4 (jsonparse@0.0.5)
└── signalk-schema@0.0.1 (tv4@1.1.9, chai@1.9.2)

nmea0183-signalk@0.2.4 node_modules/nmea0183-signalk
├── signalk-multiplexer@0.1.10
└── ggencoder@0.1.6 (async@0.9.0, jison@0.4.15)

mdns@2.2.8 node_modules/mdns
├── bindings@1.2.1
└── nan@1.5.3



Best regards.

**Comment by manuprendlair** [comment]
Hello,

To pass this install error I installed this:
sudo apt-get install libavahi-compat-libdnssd-dev

and the install seem to work :

opencpn@blueocean-nav:~/signalk/signalk-server-node$ npm install
npm WARN package.json express-namespace@0.1.1 No repository field.
npm WARN package.json n2k-signalk@0.0.0 No repository field.
 
> mdns@2.2.8 install /home/opencpn/signalk/signalk-server-node/node_modules/mdns
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/opencpn/signalk/signalk-server-node/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_browse.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_enumerate_domains.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_get_addr_info.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_process_result.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_sock_fd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_register.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_resolve.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/mdns_utils.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/network_interface.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/socket_watcher.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_create.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_set_value.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_get_length.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_buffer_to_object.o
  SOLINK_MODULE(target) Release/obj.target/dns_sd_bindings.node
  SOLINK_MODULE(target) Release/obj.target/dns_sd_bindings.node: Finished
  COPY Release/dns_sd_bindings.node
make: Leaving directory '/home/opencpn/signalk/signalk-server-node/node_modules/mdns/build'
n2k-signalk@0.0.0 node_modules/n2k-signalk
├── nomnom@1.6.2 (colors@0.5.1, underscore@1.4.4)
├── JSONStream@0.7.4 (jsonparse@0.0.5)
└── signalk-schema@0.0.1 (tv4@1.1.9, chai@1.9.2)

nmea0183-signalk@0.2.4 node_modules/nmea0183-signalk
├── signalk-multiplexer@0.1.10
└── ggencoder@0.1.6 (async@0.9.0, jison@0.4.15)

mdns@2.2.8 node_modules/mdns
├── bindings@1.2.1
└── nan@1.5.3

Best regards.
