### ISSUE TITLE
Plugin informational messages

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#408]
A plugin's configuration is now fire and forget - it either works or doesn't, no way to add feedback to the plugin configuration form. The only way to get any feedback is from the server log.

There are also times when a plugin might want to add dynamic information to the configuration ui: for example a list of available sensors' ids that can be activated. 

A poor man's solution is to provider these in the ui for the user to copypaste to a form field. 

A richer solution would be to incorporate dynamic data into the form's input as data, not just informational text, allowing the code to use that, for example as enum values in the plugin config schema.

It would be straightforward to support messaging from a plugin via serverevents to the configuration ui.

**Comment by sbender9** [comment]
A plugin can currently provide dynamic configuration data. For example: https://github.com/sbender9/signalk-derived-data/blob/master/index.js#L140

**Comment by tkurki** [comment]
I admit I did not remember that, but getting that to display on the screen requires a reload, I think.

**Comment by tkurki** [comment]
https://github.com/SignalK/signalk-server-node/blob/master/SERVERPLUGINS.md#appsetproviderstatusmsg
