### ISSUE TITLE
Add server version to the Admin UI

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#433]
It would be useful to be able to check the server version from the UI.

**Comment by zubenubi** [comment]
Is the  server version you are referring to the 'release' version? Is that currently available in the signalk-server-node code?

**Comment by tkurki** [comment]
Yes, the version is in package.json and available in /signalk response per Signal K specification:

![image](https://user-images.githubusercontent.com/1049678/36432971-2271373a-1664-11e8-8001-33f15632f5b0.png)

There is one problem though: the version is updated on publishing to npm and after that the master version in Github still advertises that same version, even if there are additioanl changes.

**Comment by zubenubi** [comment]
Should the version be present on the Dashboard or Footer or within the Server menu ? Preferred location?

**Comment by zubenubi** [comment]
Im not certain as to how to edit the admin app files. Here is what I have tried:
-clone signalk-server-node-admin-app
-run npm link in signalk-server-node-admin-app folder. Some complaints wrt jquery missing
-run 'npm link @signalk/server-admin from signalk-server-node folder
-Run signalk-server-node with changes to Footer.js not being shown
-Try to run signalk-server-node-admin-app - no joy

Would it be preferable to ask this in slack?

**Comment by tkurki** [comment]
(handled in slack)
