### ISSUE TITLE
List available serial ports in admin provider configuration

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#449]
`serialport` can list available serial ports, so we could use that to populate a list of serial ports in provider configuration form instead of forcing the user to figure this out himself.

**Comment by tkurki** [comment]
https://www.npmjs.com/package/serialport#serial-port-list

**Comment by webmasterkai** [comment]
When the Admin UI loads in the browser it makes some requests to the server for various bits of information.
```javascript
export function fetchAllData (dispatch) {
  fetchPlugins(dispatch)
  fetchWebapps(dispatch)
  fetchApps(dispatch)
  fetchLoginStatus(dispatch)
  fetchServerSpecification(dispatch)
}
``` 
Should it be added to one of those endpoints or should a new endpoint be created?

**Comment by tkurki** [comment]
Hmm. Serial ports list does not fit well into anny of those. Maybe create a new one? Then just the configuration panel can access it separately, and we can add a <Refresh> button in the panel/poll/use a serverevent to inform that the list has changed. Getting slightly ahead of myself here...

**Comment by mpvader** [comment]
Hey I think this is a great idea, and it would be a great help to make things easier for the novice user.

Make sure to show some of the extra available data so people can identify their device.

And a refresh button, so someone can unplug / replug their device to see what’s what.

Lastly, it would be nice to have an alert besides data providers on the overview page and/or on the detail config page, in case configured for a non existing port.
