### ISSUE TITLE
Sample Data Scripts not working

### ISSUE THREAD

**Issue by Krillle** [SignalK/signalk-server-node#458]
The sample providers scripts in bin don't start any more:
`pi@signalk:/usr/lib/node_modules/signalk-server $ ./bin/nmea-from-file`
`{ Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/signalk-server/plugin-config-data'`
`    at Object.fs.mkdirSync (fs.js:885:18)``

`pi@signalk:~ $ signalk-server -s settings/aava-file-settings.json`
`{ Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/signalk-server/plugin-config-data'`
`    at Object.fs.mkdirSync (fs.js:885:18)`
`    at ensureExists (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:78:10)`

**Comment by tkurki** [comment]
This is actually by design, there is now `signalk-server --sample-nmea0183-data` if you want to use the sample data. The scripts in `bin` are usable if you set up the server for development from git, not with npm.

**Comment by Krillle** [comment]
The sample data provided there is quite few. How to uses the other samples "aava-n2k.data" or "plaka.log" now?

**Comment by tkurki** [comment]
sample-nmea0183-data is plaka.log

No handy option exists for N2K - would you be able to add one and create a PR for it? See https://github.com/SignalK/signalk-server-node/blob/a168004d91940521886047a67228da0f22d53892/lib/config/config.js#L51

**Comment by Krillle** [comment]
Yeah, I can do that. In which branch should I edit?

**Comment by Krillle** [comment]
Installing Signal K Server via GIT is what I did, where it doesn't work, btw:
```git clone https://github.com/SignalK/signalk-server-node.git
cd signalk-server-node
npm install && npm run prepublishOnly```

**Comment by tkurki** [comment]
Your original description says `pi@signalk:/usr/lib/node_modules/signalk-server` where the global install puts stuff.

**Comment by Krillle** [comment]
Yes, there it is put.

**Comment by tkurki** [comment]
Git clone method does not result in installation under /usr/lib.

**Comment by Krillle** [comment]
It is in /usr/lib/node_modules/signalk-server/

**Comment by tkurki** [comment]
My guess is that you installed with `sudo npm install -g` instead of just `npm install`. That would create /usr/lib/node_modules as part of the global -g install.

**Comment by Krillle** [comment]
Ah, sorry my fault. I mixed it up with the EmpirBus Plugin git.
