### ISSUE TITLE
bug: invalid default uuid and incorrect help text on Vessel data screen

### ISSUE THREAD

**Issue by bkp7** [SignalK/signalk-server-node#467]
On the admin screen under Server, Vessel data the text against UUID states that UUID is not used if MMSI is set, however it is actually used in the uuid property within the vessel schema even if the mmsi is present.

In addition the default uuid of `urn:mrn:signalk:uuid:2204ae24-c944-5ffe-8d1d-4d411c9cea2e` is not a valid Signal K uuid because it is version 5 (namespace name-based) rather than version 4 (random). To fix change the default uuid to something like `2204ae24-c944-4ffe-8d1d-4d411c9cea2e`.

The presence of the version 5 uuid causes the json output at http:/.../signalk/v1/api` to be invalid.

**Comment by sbender9** [comment]
After a discussing with @tkurki , I'm closing that PR. I will fix the help text instead.
