### ISSUE TITLE
bin scripts require bash

### ISSUE THREAD

**Issue by lsoltero** [SignalK/signalk-server-node#47]
not all embedded systems can run bash.  the shell scripts including in the distribution directory should be re-written to use sh syntax.

**Comment by tkurki** [comment]
The functionality is minimal, easy to fix. PR?

**Comment by lsoltero** [comment]
happy to send patches if you want me to do this. basically we redo 
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
and replace it with
DIR=`dirname $0`
cd $DIR
$DIR/signalk-server -s ./settings/actisense-serial-settings.json $*

and then replace
#!/bin/bash for #!/bin/sh

**Comment by tkurki** [comment]
Sure, nothing beats the smell of easily merged Pull Requests in the morning. Or any time of the day for that matter...

**Comment by lsoltero** [comment]
the following patch uses readlink to make shell independent startup scripts.

diff --git a/bin/actisense-serial-n2kd b/bin/actisense-serial-n2kd
index e35e159..a5b0d9d 100755
--- a/bin/actisense-serial-n2kd
+++ b/bin/actisense-serial-n2kd
@@ -1,2 +1,3 @@
-#!/bin/bash
-actisense-serial /dev/tty.usbserial-1FD34 | analyzer -json | tee >(n2kd)
\ No newline at end of file
+#!/bin/sh
+actisense-serial /dev/tty.usbserial-1FD34 | analyzer -json | tee >(n2kd)
+
diff --git a/bin/n2k-from-actisense b/bin/n2k-from-actisense
index e63d5fe..defa6a0 100755
--- a/bin/n2k-from-actisense
+++ b/bin/n2k-from-actisense
@@ -1,4 +1,7 @@
-#!/bin/bash
+#!/bin/sh
+
+SP=`readlink -f $0`
+DIR=`dirname $SP`
+cd $DIR/..
+$DIR/signalk-server -s ./settings/actisense-serial-settings.json $*
 
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-$DIR/signalk-server -s ./settings/actisense-serial-settings.json $*
\ No newline at end of file
diff --git a/bin/n2k-from-file b/bin/n2k-from-file
index aa1e290..622d6ef 100755
--- a/bin/n2k-from-file
+++ b/bin/n2k-from-file
@@ -1,4 +1,7 @@
-#!/bin/bash
+#!/bin/sh
+
+SP=`readlink -f $0`
+DIR=`dirname $SP`
+cd $DIR/..
+$DIR/signalk-server -s ./settings/aava-file-settings.json $*
 
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-$DIR/signalk-server -s ./settings/aava-file-settings.json $*
\ No newline at end of file
diff --git a/bin/nmea-from-file b/bin/nmea-from-file
index 34340f2..ab13b6f 100755
--- a/bin/nmea-from-file
+++ b/bin/nmea-from-file
@@ -1,4 +1,7 @@
-#!/bin/bash
+#!/bin/sh
+
+SP=`readlink -f $0`
+DIR=`dirname $SP`
+cd $DIR/..
+$DIR/signalk-server -s ./settings/volare-file-settings.json $*
 
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-$DIR/signalk-server -s ./settings/volare-file-settings.json $*
\ No newline at end of file
