### ISSUE TITLE
Copy/paste typo in electrical.batteries 

### ISSUE THREAD

**Issue by Krillle** [SignalK/signalk-server-node#478]
`electrical.batteries.<reg>.voltage.meta.description` is `"Voltage measured at or as close as possible to the device"`
As far as to my physical knowledge this might concern really big boats, or must be be a copy paste error from battery temperature.

**Comment by tkurki** [comment]
No, this is intentional. On a 12 v dc system with possibly inadequate wiring where in the circuit you measure voltage may cause substantial differences.

Then again we don’t have a path for voltage measurement somewhere else in the circuit.
