### ISSUE TITLE
note: Firefox and Admin-UI

### ISSUE THREAD

**Issue by Dirk--** [SignalK/signalk-server-node#486]
in case, settings are made, firefox responds with blank page and notes 'ReferenceError: event is not defined':
pages involved
- /admin/#/serverConfiguration/providers
- /admin/#/security

**Comment by tkurki** [comment]
Could you post more clear instructions on what to do to replicate the issue?

**Comment by Dirk--** [comment]
Hope, this makes it clear:
On an fresh install, I can call  provider url to add.
As soon as I added a provider, I can not call provider url again (blank page).
Using Chrome, everything works as expected.

**Comment by free-x** [comment]
@Dirk-- @tkurki 
can confirm this behavior. I have no other browser except firefox under linux and have wondered

**Comment by Dirk--** [comment]
issue is at:
firefox 58.0.2 windows7
firefox 59.0.2 ubuntu

details on my fresh installation (2018-03-26):
https://bastelbude.grade.de/mediawiki/index.php?title=OpenPlotter#blackBox
