### ISSUE TITLE
admin-ui generated canboatjs provider

### ISSUE THREAD

**Issue by Dirk--** [SignalK/signalk-server-node#489]
admin-ui generated canboatjs provider does not work:

`{
      "id": "canboatjs",
      "pipeElements": [
        {
          "type": "providers/simple",
          "options": {
            "logging": false,
            "type": "NMEA2000",
            "subOptions": {
              "type": "canbus-canboatjs",
              "interface": "vcan0"
            }
          }
        }
      ],
      "enabled": true
    }
`

this one does the job well:

`{                                                                           
      "id": "canbus-canboatjs",                                          
      "enabled": true,                                                          
      "pipeElements": [                                                         
        {                                                                       
          "type": "providers/canbus",                                           
          "options": {
            "canDevice": "vcan0"
          }                                                                     
        },                                                                      
        {                                                                       
          "type": "providers/canboatjs"                                         
        },                                                                      
        {                                                                       
          "type": "providers/n2k-signalk"                                       
        }                                                                       
      ]                                                                         
    }`

Signal K Server version 1.1.1

**Comment by sbender9** [comment]
Do you get any errors? Or just don't get data?

**Comment by sbender9** [comment]
OK, I think I found the issue. If you manually change that `interface` setting to be called `canDevice` it should work. Will get a fix out ASAP.

**Comment by sbender9** [comment]
Sorry, make it `device`

**Comment by Dirk--** [comment]
yes, this does the job: and I am getting data
`
{
      "id": "canboatjs",
      "pipeElements": [
        {
          "type": "providers/simple",
          "options": {
            "logging": false,
            "type": "NMEA2000",
            "subOptions": {
              "type": "canbus-canboatjs",
              "device": "vcan0"
            }
          }
        }
      ],
      "enabled": true
    }`
