### ISSUE TITLE
Setup writes faulty security setting

### ISSUE THREAD

**Issue by Krillle** [SignalK/signalk-server-node#504]
The setup via `sudo signalk-server-setup` throws exception:
`/usr/bin/signalk-server-setup: line 38: [: ==: unary operator expected`

After setup signal k server is starting but not showing provider settings.
After deleting the following lines in settings.json the server works normally:
```
  "security": {
    "strategy": "@signalk/sk-simple-token-security"
  }
```

Bug reproduced  in two clean installs

**Comment by sbender9** [comment]
The security setting is correct. That is supposed to be there. When you first hit the server, it should asking you to create a admin user and password? Then once you login you will see the provider settings.

Not sure exactly what that error means...

**Comment by sbender9** [comment]
Can you tell exact what you're entering for each of the prompts in setup?

**Comment by Krillle** [comment]
There was no asking for create a admin user and password.
Instead there was an exception in the logs. I don't remember wich one, sorry.

I entered Only friendly stuff:
Name: Ibelle 
MMSI: 211598410
Port: 3000
SSL: no

**Comment by sbender9** [comment]
It asks to create admin account the first time you hit the admin ui

**Comment by sbender9** [comment]
Can you get a screenshot of the admin ui?

And check the URL that's in your browser.

**Comment by sbender9** [comment]
Also, try restarting your browser before you hit the admin ui. There may be old/broken cookies from a previous install.

**Comment by tkurki** [comment]
Is this still valid?

**Comment by Krillle** [comment]
Newer fresh installs did not show this issue any more. So closing is fine.
