### ISSUE TITLE
Raspberry Tutorial

### ISSUE THREAD

**Issue by netAction** [SignalK/signalk-server-node#509]
I am talking about this:

https://github.com/SignalK/signalk-server-node/blob/master/raspberry_pi_installation.md

There are demo files mentioned that don't work when they are simply added in web configuration interface.
To use the demo files, the user has to setup canboat first: https://github.com/canboat/canboat/wiki/Building

It is unclear how to setup the data providers to use the demo files. Screenshots or snippets of .signalk/settings.json would be nice.

Signalk.socket will not start in the suggested order:

    $ sudo systemctl start signalk.service
    $ sudo systemctl start signalk.socket

This only works in the other order.

**Comment by tkurki** [comment]
canboat is no longer needed thanks to #512

**Comment by tkurki** [comment]
There are startup scripts in the `bin`  directory for both nmea0183 and n2k files, but we dropped the instructions for using them when we switched to
- recommending a global install from npm
- (more frequent version publishing)
there is now the `--sample-nmea0183-data` command line switch in the documentation. Another switch exists for the n2k sample file: `sample-n2k-data`. Do you think it would be useful to add that?

All in all we have purposefully moved away from trying to document the settings files and instead brought all the configuration options to the admin UI. People say that JSON is human readable, but it is not layman writable, judging from the trouble people have had splicing together their own settings files.

So I don't think adding more documentation about the settings files is worth the effort. Those who venture that far will hopefully where to ask for help and if the number of questions rises we can address that. There are already several different examples.

The trouble with detailed instructions is that they grow frequently outdated.
