### ISSUE TITLE
Help for adding self made data

### ISSUE THREAD

**Issue by joabakk** [SignalK/signalk-server-node#52]
Hi,

I want to aggregate nmea0183 and possibly n2k data, but also some of my own data. It's all well and good to expand 0183 sentences and n2k sentences, but at some stage people will want to add custom data to the stream. I am looking for a simple way of adding data, type "select category, name the variable, update the data" in order to add the data into the right format and into the server stream. Am I on the right track?

**Comment by tkurki** [comment]
I think the way to go about it would be to figure out a decent format for your data that it is line with the rest of the Signal K data model and then propose a schema change.

After all the point of the Signal K spec is to specify how a certain data item should be presented. If we resort to just stuffing arbitrary values into the messages then what's the point of a common model.

Am I answering your question at all? 

Could you give a concrete example of something that you would like to represent in the Signal K model that is not there at the moment?

**Comment by tkurki** [comment]
Hmm or are you looking for just a way to send data to the server, eg. make a custom Provider? 

One easy way to do that would be to create an executable that outputs Signal K delta in json format, one message per line. Then you could create a settings file that could use the `execute` provider to launch your application. 

`execute` provider is configured like in https://github.com/SignalK/signalk-server-node/blob/b7c8cedc6f72c863fe65980082c88ecc2954e2c2/settings/actisense-serial-n2kd-settings.json#L10. By using a somewhat similar provider pipeline (without n2k-signalk) you could have your application's output chopped to a message per line and the json parsed to delta objects that the server can digest.

If you need I can create a simple settings file that will echo a static delta message continuously to demonstrate the idea.

**Comment by joabakk** [comment]
Thank you. You are making perfect sense. I agree to align and add to the schema and will do. And to your second comment, yes please!

**Comment by tkurki** [comment]
Any progress on this? Do you still need help actively?

**Comment by joabakk** [comment]
I have not come any further. I would like a pointer to how I can tell sk to add some data like polar speed and target speed from a Python script or similar

**Comment by tkurki** [comment]
Actually I just remembered that there has been a sample settings file that launches a shell script to inject dummy Signal K data. See https://github.com/SignalK/signalk-server-node/blob/master/settings/commandline-provider-settings.json
