### ISSUE TITLE
feat: Support Serial Port Plug-N-Play w/ Auto Start/Restart 

### ISSUE THREAD

**Issue by webmasterkai** [SignalK/signalk-server-node#522]
If there is configuration for a specific serial port but it is not found periodic polling should auto enable when it is plugged in. Similarly, if the port has an issue and temporarily disconnects it should start working again when it becomes available. Related to #519 and #449.
Currently if I unplug an active port and then plug it back in nothing happens. The server doesn't reconnect to it.

Should serial ports be a plugin like the `net` plugin?

**Comment by tkurki** [comment]
Another adpect to this is that serial devices must now be available when the server starts. We should support later attachment.

Maybe a better name would be serial port hot plug support?

Then again there’s been little demand for this, I can recall only one support request related to a flaky usb device.

**Comment by webmasterkai** [comment]
It'll be important in the future for automatic discovery of USB devices. Plugin an Actisense NGW-1 device and the server auto configures a provider for that device.

Also, every time I power on my VHF Radio the USB connection on my AIS flakes out and I have to restart the server.

**Comment by tkurki** [comment]
Serial devices are now retried per #697 and autodetect is tracked in #863
