### ISSUE TITLE
refactor: consider switching to jest for testing

### ISSUE THREAD

**Issue by webmasterkai** [SignalK/signalk-server-node#525]
Since the admin interface is React it might be useful to use [Jest](https://facebook.github.io/jest/) for server and web client.

- [react friendly](https://spin.atomicobject.com/2017/05/02/react-testing-jest-vs-mocha/)
- [speed](https://medium.com/airbnb-engineering/unlocking-test-performance-migrating-from-mocha-to-jest-2796c508ec50)
- [stackshare](https://stackshare.io/stackups/jest-vs-mocha)
- [easily converted](https://github.com/skovhus/jest-codemods)

**Comment by tkurki** [comment]
While a good suggestion I don't think this needs an open issue to track this.
