### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#53]
"As mentioned yesterday, I did a re-install from scratch. It is hard to say where the problems started, but my assumption is, that the issues where cause by strictly following the installation procedure from the signal K website.
 
$ sudo apt-get update
$ sudo apt-get install curl git build-essential
$ curl -sL https://deb.nodesource.com/setup | sudo bash -
$ sudo apt-get install nodejs
 
In the first trial, I ran apt-get install nodejs. This time, I stopped after installing the build-essentials and  followed the installation procedure for nodejs for RASPI at
https://learn.adafruit.com/node-embedded-development/installing-node-dot-js
Interesting enough, it run through this time. So obviously, the sudo apt-get install nodejs left something irreversible in the system.
I think it would be helpful for other users of RASPI to make a clear comment in the installation description to follow the alternative path."

**Comment by timmathews** [comment]
I update the instructions on [signalk.org](http://signalk.org/installation.html) today and verified that it works OK on a fresh RPi install. I think we can close this.

However, it's still a pretty old (v0.12) version of Node.js we're telling folks to install. Is there any reason not to go with the 14 or 15 branches?

**Comment by tkurki** [comment]
#73
