### ISSUE TITLE
duplicated plugins

### ISSUE THREAD

**Issue by sailoog** [SignalK/signalk-server-node#547]
![captura de 2018-05-17 20-18-57](https://user-images.githubusercontent.com/8145560/40196157-f9a582d0-5a0f-11e8-98c7-93272d9318fd.png)
SK server installed and updated from npm
simple-gpx and gpxload plugins are duplicated
available set-system-time plugin is 1.0.0 but the installed version is 1.2.0

**Comment by tkurki** [comment]
Duplicated plugins is a server issue: the gpx modules are both plugins and webapps, as the icons show, but they should be listed just once.

**Comment by sailoog** [comment]
ok, sorry, closing open plugin issues.

**Comment by tkurki** [comment]
There were both `set-system-time` and `@signalk/set-system-time`. I published non-signalk-plugin version of `set-system-time` and furthermore deprecated it, it should no longer be a problem. `@signalk/set-system-time` is installed as part of the server install.

**Comment by tkurki** [comment]
Fixed in #550
