### ISSUE TITLE
Multiple sources, selecting old value (bug?)

### ISSUE THREAD

**Issue by joabakk** [SignalK/signalk-server-node#556]
I see that on some values, the selected value is the oldest of the two, for example: 
```
"speedThroughWater": {
	"meta": {
		"units": "m/s",
		"description": "Vessel speed through the water"
	},
	"value": 4.156712164144859,
	"$source": "Main GPS.II",
	"timestamp": "2018-06-10T02:18:36.151Z",
	"sentence": "VHW",
	"values": {
		"Nexus.II": {
			"value": 0,
			"sentence": "VHW",
			"timestamp": "2018-06-11T05:58:32.510Z"
		},
		"Main GPS.II": {
			"value": 4.156712164144859,
			"timestamp": "2018-06-10T02:18:36.151Z",
			"sentence": "VHW"
		}
	}
}
```

**Comment by tkurki** [comment]
Where does the data & the timestamps come from? Can you provide a log file that reproduces this issue?

**Comment by joabakk** [comment]
Unfortunately, the logging was switched off before this occured. Closing and will open a new one if it happens again

**Comment by tkurki** [comment]
Hmm. On second thought could be a bug related to deltacache. Ping @sbender9.
