### ISSUE TITLE
Facilitate 3rd party providers

### ISSUE THREAD

**Issue by codefoster** [SignalK/signalk-server-node#557]
I submitted issue 548 regarding making the Node.js Signal K server more modular. I'm actually doing pretty well with that since @tkurki told me about the `SIGNALK_NODE_CONFIG_DIR` environment variable.

Similarly, though, I think it makes sense to be able to `npm install` piped providers instead of relying on them being present in the library.

Currently (as long as my limited understanding is correct), if I want to create a piped provider I need to...

1. Create it

1. Add it to my providers collection by either...

    * adding it to the Signal K library (not possible if you're using `require` to pull in the library) or

    * adding it using the providers interface

1. Register the provider in your `settings.json` file

I think it makes sense to be able to follow these steps...

1. Install a piped provider from npm (i.e. `npm install myCustomProvider`)

    * This could obviously be pulled in using `npm link` just like you do with plugins already.
    
    * Providers could use a keyword like `signalk-node-provider` also like plugins already use `signalk-node-plugin`

1. Register the provider in your `settings.json` file.

    The library code currently looks at the `type` property of a provider and uses that to determine the location and name of the provider. I don't think it would be a problem if the library simply enumerated all built-in providers (those in the `/providers` directory) and all 3rd party providers (those in `/node_modules`) and allowed me to include them by name. Naming overlaps could be easily handled by the developer.

Additionally (and this may make more sense as a separate issue), I think it makes sense to be able to register a provider with the server not only by specifying it in the settings.json file, but also directly on the server object. Something like...

```js
let server = new SignalKServer();
server.provider("myCustomProvider") //register the 'myCustomProvider' provider which will have been loaded from the node_modules folder
```

I'm suggesting this issue to get core contributor feedback on the sanity of the approach. I'm willing to submit a PR.

**Comment by webmasterkai** [comment]
Why not just create a plugin for the custom provider?

**Comment by codefoster** [comment]
Hold the phone. I just noticed that `pipedProvider.js:56` already attempts to `require` the provider and if it fails it looks in the `/providers` directory. That'll do it!

**Comment by tkurki** [comment]
Yes sir, just don’t prefix with providers and it will work.
