### ISSUE TITLE
feature request: send data to identified interfaces

### ISSUE THREAD

**Issue by joabakk** [SignalK/signalk-server-node#558]
Many nmea0183 devices need one or two sentences from other units, but if many more are sent, they repeat the sentences as their own (same source albeit different sentence and id). Today, one can only send sentences to all nmea0183 devices, as opposed to directing them to the units that need specific sentences from other sensors

**Comment by tkurki** [comment]
I believe https://www.npmjs.com/package/nmea0183-to-nmea0183 does what you want. If not then maybe it can be extended to include $source specifier.

**Comment by joabakk** [comment]
Indeed, I had missed that
