### ISSUE TITLE
Deleted Admin Account --> How to set new user without access to the GUI? 

### ISSUE THREAD

**Issue by briantilburgs** [SignalK/signalk-server-node#559]
Hi All,

I know this is not a software issue (maybe documentation or google not able to find the information) but i need a bit of help.

I managed to delete the admin user that I created to start using authentication.
Then decided that I didn't wat the authentication on the Little Raspberry pi in my boat so I deleted the only admin user.

Running openplotter with signal inside. tried to do an install on other raspberry to get the security.json for a copy but this sets a password that I don't know... What is de the default password??

Thanks for the help.

Brian

**Comment by sailoog** [comment]
Are you asking for the default signal k user password in openplotter?
https://docs.sailoog.com/openplotter-v1-x-x/getting-started/first-settings#signal-k-settings

**Comment by sbender9** [comment]
For future reference, you can delete the security.json file, you'll then be promted to create a new admin user when you first hit the admin ui,

@sailoog you should also make your install not include a security.json. Default users/passwords are a bad idea IMHO.

**Comment by sbender9** [comment]
@sailoog  This also means that every one of you users has the same encryption key and can easily be hacked.

**Comment by briantilburgs** [comment]
Hi, The Sailoog install didn't have a password until I'd set one for testing..

I managed to delete the security part from the settings file.. That helps also.
Didn't dare to delete the security file..

**Comment by tkurki** [comment]
Added a note about removing `security.json` in cda6014174582e963e09a236f5f863fcbfd34202. OpenPlotter default credentials is a separate issue.
