### ISSUE TITLE
Enabling SSL from Server->Settings issues w/ systemd

### ISSUE THREAD

**Issue by Knobee** [SignalK/signalk-server-node#587]
I've discovered that if you use "signalk-server-setup", it installs a systemd configuration that is hard-wired to port 3000.  If an administrator enables SSL, the port numbers on the web page are ignored, and SSL is enabled on port 3000.

I'm not sure if it's possible for the server to determine if it is running under systemd and modify the page presented, but it confused me a bit having run the server stand-alone and having the 3000/3443 work as expected, and then switching to systemd where it didn't.

**Comment by sbender9** [comment]
This has been fixed.
