### ISSUE TITLE
Todo: improve configuration handling

### ISSUE THREAD

**Issue by fabdrol** [SignalK/signalk-server-node#6]
Configuration is quite important, but right now it's not standardised and definitely not easy to use. Not a problem a.t.m., but if there would be a multitude of providers to choose from this would become an issue.

Todo:
- Create a way for Provider authors to register custom CLI flags
- Namespacing of config keys, to prevent collisions between Providers
- Implement a GUI to edit the server config at runtime
- Spin config off into a separate NPM module

**Comment by tkurki** [comment]
Closing as too vague & broad. Some issues already addressed by PipedProvider configuration.
