### ISSUE TITLE
execute piped provider no longer working?

### ISSUE THREAD

**Issue by mauroc** [SignalK/signalk-server-node#60]
looks like the "provider/execute" pipedProvider may have picked up a problem in one of the latest commits.

For instance, the command
```
bin/signalk-server -s settings/commandline-provider-settings.json
```
causes the server to crash after a few seconds with an out of memory error

```
==== JS stack trace =========================================

Security context: 0x39185c51 <JS Object>
    2: /* anonymous */(aka /* anonymous */) [/home/mauro/signalk-server-node/node_modules/signalk-multiplexer/node_modules/lodash/index.js:~2359] [pc=0x47a1e268] (this=0x391080c9 <undefined>,srcValue=0x391080c9 <undefined>,key=105138106)
    3: arguments adaptor frame: 3->2
    4: arrayEach(aka arrayEach) [/home/mauro/signalk-server-node/node_modules/signalk-multiplexer/node_modules/lodash/index.js...

FATAL ERROR: invalid array length Allocation failed - process out of memory
````
I also tried with simple Unix commands such as tail -f, which used to work correctly in previous commits.

**Comment by tkurki** [comment]
Mea culpa, multiplexer commit on Jan 9. I'll fix it asap and let you know.

**Comment by tkurki** [comment]
This was fixed by https://github.com/SignalK/signalk-multiplexer-node/commit/7e3f8a49d8e75eab92d97744077dcee401afacf0
