### ISSUE TITLE
Server advertises wrong port when running behind a reverse proxy

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#61]
Node server reports the actual port it is listening on. For situations like at demo.signalk.org, where it is running behind a reverse proxy, the port reported is the internal port, not what is accessible from the outside.

**Comment by tkurki** [comment]
#75 took care of the `/signalk` metadata problem, but mdns advertisements should use the proxy host & port as well.

**Comment by timmathews** [comment]
#78 fixed this right?
