### ISSUE TITLE
appstore not installing apps.

### ISSUE THREAD

**Issue by cons2006** [SignalK/signalk-server-node#626]
In signalk-server-node/lib/interfaces/appstore.js on line 50 the appstore is waiting for a POST but a GET is send to install an app. See line 370.

**Comment by sbender9** [comment]
That code is not actually used and needs to be removed. It is from the old admin user interface. New code is in packages/server-admin-ui

App install is working fine, you may be having some other issue?

**Comment by tkurki** [comment]
/appstore still loads and there installation is not working. Let's just get rid of the poor thing.

**Comment by tkurki** [comment]
Fixed in bb444705a04630d9eb9aae634b4e9dafbbb33927.
