### ISSUE TITLE
Server as a TCP server for NMEA0183 data

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#637]
Apparently there are use cases where this might come in handy, for example when you use iSailor as your course computer and you want NMEA0183 data, like wind, available in iSailor and you want iSailor generated autopilot sentences routed to your serial connection via the same tcp connection.

**Comment by newt2u** [comment]
I have 2 problems in the scenario tkurki outlined. The first is allowing bidirection comms on 10110, the other is getting the autopilot data back out on a NMEA serial link. Can’t do the latter without sending everything out, AIS and all. So filtering sentences out on the serial link would also be required. Current workaround is to do autopilot input and output filtering in opencpn

**Comment by newt2u** [comment]
Sorry, perhaps it should be in another thread. I’m new here

Bidirectionality lets autopilot data in from isailor. Filtering allows its output to a legacy autopilot without flooding a 4.8k link. For this issue very much related.

**Comment by tkurki** [comment]
Implemented in #639
