### ISSUE TITLE
Run on Windows 10 of Linux PC??

### ISSUE THREAD

**Issue by jcdocka** [SignalK/signalk-server-node#654]
Can signalk-server-node be run directly on a pc, or does it have to be run on a SOC like a raspberry pi?

**Comment by tkurki** [comment]
It should be usable just by installing Node.js and starting it. Nobody in the development team uses Windows, so I can't vouch for it, but we have received some changes over time where we have inadvertedly made something not portable.

There is no underlying reason for it not to work on Windows. Changes to make it more Windows friendly, like adding  documentation on how to install it, are welcome.
