### ISSUE TITLE
Help with Subscription Protocol.

### ISSUE THREAD

**Issue by dmdelorme** [SignalK/signalk-server-node#680]
I have a esp32 with wind sensor sending NMEA wind data to openplotter via port 10110.
I want to a read the signalK value of sensors.anchorLight from the ESP32 .
What port should i use any other info would help..

**Comment by dmdelorme** [comment]
I have a esp32 with  wind sensor sending NMEA wind data to openplotter via port 10110.
I want to  a read the signalK value of sensors.anchorLight from the ESP32 .
What port should i use any other info would help..

**Comment by dmdelorme** [comment]
"If the client is http capable the REST API is a good choice, or use get/list/put messages over WebSockets or TCP"
I am trying to understand this 
if I `http://openplotter:3000/signalk/v1/api/.` i will get a json object of every thing...
How do i just get the key i want for example or better yet the value?
`"sensors": {
        "anchorLight": {
          "value": 0,
          "$source": "OPnotifications.GPIO.output.25",
          "timestamp": "2018-12-09T15:14:50.591Z",
           }`

**Comment by tkurki** [comment]
Like this: http://node-master.signalk.org/signalk/v1/api/vessels/self/navigation/position/value

I’ll need the computer for the subscription example..

**Comment by tkurki** [comment]
Connect to `http://openplotter:3000/signalk/v1/api/signalk/v1/stream?subscribe=none` via WebSocket and send the string `{"context": "vessels.self","subscribe": [{"path": "your.path.here"}]}` from the client to the server. Upon connection you will get the server's hello message.

After you get wifi connection you can estabalish the ws connection and then retrieve the latest value via http, you won't get anything from the ws until the value changes and there is a delta being sent.

**Comment by dmdelorme** [comment]
I will try that 

> http://openplotter:3000/signalk/v1/api/vessels/self/sensors/anchorLight/

yup that worked thanks i get the following.
`{
  "value": 0,
  "$source": "OPnotifications.GPIO.output.25",
  "timestamp": "2018-12-09T15:14:50.591Z",
  "values": {
    "OPnotifications.GPIO.output.21": {
      "value": 0,
      "timestamp": "2018-12-09T14:37:27.686Z"
    },
    "OPnotifications.GPIO.output.25": {
      "value": 0,
      "timestamp": "2018-12-09T15:14:50.591Z"
    }
  }
}`
I think the last 2 values are stale.

**Comment by tkurki** [comment]
Use triple backticks on separate lines to keep line formatting. (I fixed it for you)

**Comment by tkurki** [comment]
You may notice that the first value/$source/timestamp are the same as 
 the value and timestamp under `OPnotifications.GPIO.output.25`.

You have two different sources producing `sensors/anchorLight`, that is why there is `values` and data from both those sources under it. The top `value` will always be the latest value.

`sensors/anchorLight` does not quite make sense, as this is not a sensor, but the state of the light, right? 

We have `navigation.lights` where the value in your case should be `off` or `on`: https://github.com/SignalK/specification/blob/3d9a82a961be224012838318505d66cfc76bc150/schemas/groups/navigation.json#L141-L170

**Comment by dmdelorme** [comment]
Did a reset to clean up stale sK messages
I dont want to use a stream since i am just checking for a value and reacting to it if it has changed since the last time.
`http://openplotter:3000/signalk/v1/api/vessels/self/sensors/anchorLight`
gives me.
`{"value":0,"$source":"OPnotifications.GPIO.output.25","timestamp":"2018-12-09T23:59:31.008Z"}`
But sK play ground nor ArduinoJson.h says this is not valid but [https://jsonformatter.curiousconcept.com/](url) says is is....

`void getlight()
{
  if ((WiFi.status() == WL_CONNECTED)) { //Check the current connection status

    HTTPClient http;

    http.begin("http://192.168.1.7:3000/signalk/v1/api/vessels/self/sensors/anchorLight"); //Specify the URL
    int httpCode = http.GET();                                        //Make the request

    if (httpCode > 0) { //Check for the returning code

      String payload = http.getString();
      StaticJsonBuffer<300> JSONBuffer;                         //Memory pool
      JsonObject& parsed = JSONBuffer.parseObject(http.getString()); //Parse message
//*******************Always fails to parse raw jsonstring*******************//
      if (!parsed.success()) {   //Check for errors in parsing

        Serial.println("Parsing failed");
        delay(5000);
        //return;

      }

      const char * sensorType = parsed["anchorLight"]; //Get sensor type value
      int value = parsed["value"];                    //Get value of sensor measurement

      Serial.print("Sensor type: ");
      Serial.println(sensorType);
      Serial.print("Sensor value: ");
      Serial.println(value);
      Serial.println(httpCode);
      Serial.println(payload);
    }

    else {
      Serial.println("Error on HTTP request");
    }

    http.end(); //Free the resources
  }
}`

**Comment by dmdelorme** [comment]
Thanks for all the help I try to change to navigation.lights.
This has really helped me understand the use of the API...
