### ISSUE TITLE
How to change web service format from json to geojson

### ISSUE THREAD

**Issue by viper132** [SignalK/signalk-server-node#693]
I tried to cast geojson data via web socket. How can i change the format ?

**Comment by viper132** [comment]
How to change this format that i get from **ws://localhost:3000/signalk/v1/stream?subscribe=all
!**[annotation 2018-12-21 143900](https://user-images.githubusercontent.com/25095161/50330557-56898b80-052e-11e9-89cb-f0015b0c10cc.jpg)

To something like this
![annotation 2018-12-21 143945](https://user-images.githubusercontent.com/25095161/50330584-643f1100-052e-11e9-8949-4a8be2dd5f23.jpg) this format

Sorry, Im new with this

**Comment by viper132** [comment]
> I have no idea what you are trying to do.

How to change this format that i get from **ws://localhost:3000/signalk/v1/stream?subscribe=all
![annotation 2018-12-21 143900](https://user-images.githubusercontent.com/25095161/50330557-56898b80-052e-11e9-89cb-f0015b0c10cc.jpg)

To something like this
![annotation 2018-12-21 143945](https://user-images.githubusercontent.com/25095161/50330584-643f1100-052e-11e9-8949-4a8be2dd5f23.jpg) this format

Sorry, Im new with this

**Comment by tkurki** [comment]
See https://gist.github.com/tkurki/5b7dfac507977d7c6180bcecf383323c for an example.

If you have installed SK Node Server you can replace the file `public/examples/index.html` with it, start the server with `bin/n2k-from-file`and see a webpage with updating GeoJSON at http://localhost:3000/examples/.

**Comment by viper132** [comment]
thank you for your advice sir..  ill try it later
