### ISSUE TITLE
plugins with "signalk-plugin-enabled-by-default": true are not enabled after re-start

### ISSUE THREAD

**Issue by panaaj** [SignalK/signalk-server-node#699]
It appears that plugins that have `"signalk-plugin-enabled-by-default": true` defined in `package.json` are not actually active until the `Submit` button is clicked in the `Plugin Config` screen.

**Steps to reproduce on server v1.10.2:**

- Installed plugin which has `"signalk-plugin-enabled-by-default": true` defined in `package.json` file.
- Re-started server
- In `Server / Plugin Config` expand the section for the plugin.
- `Active` checkbox is checked as expected.
- When trying to use actions provided by the plugin they fail.
- After clicking  `Submit` in `Server / Plugin Config` then plugin becomes functional.

**Comment by tkurki** [comment]
Works on my machine.

You are missing a step from the steps to test this properly:
- make sure there is no pre-existing configuration for the plugin in your plugin-config-data directory

**Comment by panaaj** [comment]
The test was conducted on a "clean" Docker instance so there was no pre-existing configuration data.
Would it make a difference if the plugin is handling PUT requests or handling a 'non-Signal K API' route?

**Comment by tkurki** [comment]
I double checked, a bit differently but the result should be the same:
- add `"signalk-plugin-enabled-by-default": true` to an existing, installed plugin
- make sure that there is no existing config file for the plugin
- restart the server

=> the plugin is enabled (its `start` method is called as the server starts).

If you set `DEBUG=signalk:interfaces:plugins` you get debug logging of plugins loading and starting.

If I add 
```
app.get('/foo', (req, res) => {
  res.json('bar')
})
```
the endpoint works, without enabling anything in the plugin config panel.

Please provide more detail about what exactly is not working. The actual plugin code would also help...

**Comment by tkurki** [comment]
Well, those endpoints work for me, but I found something that does not: `/plugins/sksim` response is missing the `enabled` property if the plugin is enabled just by default and not from the plugins control panel.

As for api and about, this sequence works for me ok:
```
docker build -t signalk/signalk-server:latest .
mkdir .signalk && echo '{}' >.signalk/package.json && pushd .signalk && npm install sksim && popd
docker run -d  -v `PWD`/.signalk:/home/signalk/.signalk -p 3000:3000 signalk/signalk-server
curl http://localhost:3000/plugins/sksim/about
curl -X POST http://localhost:3000/plugins/sksim/api
```

**Comment by tkurki** [comment]
Is this fixed now?

**Comment by panaaj** [comment]
Seems to work fine.

**Comment by panaaj** [comment]
Confirmed this now works as expected in v1.11
