### ISSUE TITLE
PUT to signalk/v1/auth/logout responds with 401: unauthorized

### ISSUE THREAD

**Issue by panaaj** [SignalK/signalk-server-node#714]
Server version: 1.11

Steps to reproduce:

- Enable Security on the Signal K server
- Send login request and retrieve token
- Confirmed authentication by successfully `putting` values to paths
- Send PUT to `/signalk/v1/auth/logout` 

Server responds with:

```HttpErrorResponse {headers: HttpHeaders, status: 401, statusText: "Unauthorized", url: "http://192.168.99.100:3000/signalk/v1/auth/logout", ok: false, …}```

The spec says: _"To logout, a web based client should send an HTTP PUT request to /signalk/«version»/auth/logout."_ 

I am sending a null value so not sure if this is the issue?

**Comment by sbender9** [comment]
Sound like the dokie with token is not being included in the logout request?

**Comment by panaaj** [comment]
The token is included in the header of the request which works for other successful PUT's.

**Comment by sbender9** [comment]
oh, we haven''t updated the server to the latest security spec. Does just `/logout` work?

**Comment by panaaj** [comment]
It's just logout that does not work for me.... I am placing the received token in the HTTP Header { 'Authorization': `JWT xxxxxxxx` } which works for PUTs to other paths, just not working for logout.

**Comment by panaaj** [comment]
yes `/logout` works

**Comment by sbender9** [comment]
I'll work on updating to the spec...
