### ISSUE TITLE
Installation on rPI (Node V11.1)

### ISSUE THREAD

**Issue by gdavydov** [SignalK/signalk-server-node#729]
Just tried to install on brand new rPI 3 b+. Got the following almost at the end of installation.(entire screen output)

pi@raspberrypi:~ $ git clone https://github.com/SignalK/signalk-server-node.git
Cloning into 'signalk-server-node'...
remote: Enumerating objects: 101, done.
remote: Counting objects: 100% (101/101), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 7063 (delta 36), reused 33 (delta 11), pack-reused 6962
Receiving objects: 100% (7063/7063), 6.97 MiB | 85.00 KiB/s, done.
Resolving deltas: 100% (4513/4513), done.

pi@raspberrypi:~ $ cd signalk-server-node

pi@raspberrypi:~/signalk-server-node $ npm install
(node:4565) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.79-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/signalk-server-node
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! fetch failed https://registry.npmjs.org/lint-staged/-/lint-staged-8.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/compression/-/compression-1.7.3.tgz
npm ERR! fetch failed https://registry.npmjs.org/spdy/-/spdy-4.0.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/baconjs/-/baconjs-1.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/express/-/express-4.16.4.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/signalk-server-node/npm-debug.log
npm ERR! not ok code 0

**Comment by tkurki** [comment]
Your npm is extremely old for some reason:

>npm ERR! npm -v 1.4.21

**Comment by sbender9** [comment]
https://github.com/SignalK/signalk-server-node/blob/master/raspberry_pi_installation.md

**Comment by gdavydov** [comment]
yea, re-install everything from scratch.It works now. Thank you
