### ISSUE TITLE
Update the whole Signal K Node to latest (stable) Node

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#73]
All Signal K node code specifies pretty old Node versions. We should upgrade to stable, which at the moment is 5.7.1.
- [ ] package.jsons
- [ ] installation instructions & other documentation
- [ ] travis configs

I don't think there are any code level changes needed. We could also leverage new apis like network stuff to figure out broadcast address for local network.

**Comment by joabakk** [comment]
Just tried now to update node.js and npm, without changing any other code. All the errors went away, except for zmg, which still cannot be installed. I would like to help, but I don't feel capable. But if we are changing the base versions, it is probably wise to incorporate any new dependencies also, such as mosca from #82 if we agree on that

**Comment by tkurki** [comment]
I am running node server with node 5.9 with no problems. What was the problem you encountered @joabakk?

**Comment by tkurki** [comment]
New dependencies should be added as needed, not in anticipation of some future use.

**Comment by joabakk** [comment]
![image](https://cloud.githubusercontent.com/assets/2553029/14235137/a6950114-f9f5-11e5-9927-6fd602ae29fb.png)
This is the error I got now. Used to be more

**Comment by joabakk** [comment]
I got an error from zmq, but that was related to mosca. Never mind

**Comment by tkurki** [comment]
Done....
