### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by tonybentley** [SignalK/signalk-server-node#732]
<img width="376" alt="screen shot 2019-02-08 at 1 48 00 pm" src="https://user-images.githubusercontent.com/236517/52508065-2cf0f600-2ba8-11e9-8f01-af9074085944.png">

Issues originated from uploading a GPX file in GPXLoad plugin

Suggested change is to set the upload size limit on bodyParser for Express api endpoints in lib/index.js. (see attached image)

**Comment by tkurki** [comment]
As you clearly know how to fix this why not create a Pull Request with the fix? An image is not a very maintainer friendly way to contribute, can't even copypaste from one...

**Comment by tonybentley** [comment]
PR up!
