### ISSUE TITLE
Does the TCP stream port support data updates?

### ISSUE THREAD

**Issue by bwssytems** [SignalK/signalk-server-node#740]
Thanks for all the hard work on this, an exceptional system.

Want to use the tcp port, default 3858, to be able to send singalK updates from a sensor?

I seem to not be able to do this as the signalk-server-node does not show any errors nor any error responses when sending updates messages in.

Is this available on the TCP Stream?

**Comment by tkurki** [comment]
Yes, at least it works on my machine. 

Try starting the server without any other input with `bin/signalk-server` and then `echo '{"updates":[{"values":[{"path":"navigation.speedOverGround","value":1}]}]}' | nc localhost 3858` and you should see the result like

![image](https://user-images.githubusercontent.com/1049678/53471485-6b722600-3a6d-11e9-9126-c6ec4e7dfb72.png)

**Comment by bwssytems** [comment]
Well, that works great and it seams that I must have another issue in the tcp send. Thanks!

**Comment by bwssytems** [comment]
Found my issue, the tcp stream expects a new line at the end of each JSON message.

**Comment by tkurki** [comment]
Yes, that should be added to the Signal K specification IMHO.
