### ISSUE TITLE
Need help getting NMEA0183 stream. 

### ISSUE THREAD

**Issue by nealguidry** [SignalK/signalk-server-node#746]
I've purchased the Actisense USG-2 usb. I've installed SignalK server on the newest raspberry pi. I can get the sample data file to work (nmea0183-sample-data). I've added in data providers the serial connection. The raspberry does see the usb-2 device as it shows up as /tty/USB0 from within terminal. Not seeing the incoming stream in the signalk dashboard. Who would be the best person to assist in getting this working? I'm assuming I don't have the sentence events setup quite right. 

<img width="1303" alt="signalk dashboard" src="https://user-images.githubusercontent.com/2716325/53759576-46731e00-3e86-11e9-86d4-b6bee2891003.png">
<img width="1054" alt="signalk serial connection" src="https://user-images.githubusercontent.com/2716325/53759614-5db20b80-3e86-11e9-9d9e-86bd70f51fcf.png">

**Comment by sbender9** [comment]
Your setup looks good to me.

You should leave `sentenceEvent` blank, but it would not effect 0183 input functionality.

What do you see if you type the following into the terminal: `cat /dev/ttyUSB0`

**Comment by nealguidry** [comment]
looks like I'm seeing the nmea stream.
<img width="442" alt="screen shot 2019-03-04 at 2 55 20 pm" src="https://user-images.githubusercontent.com/2716325/53762486-d9fc1d00-3e8d-11e9-8b23-c615473b9cd4.png">

**Comment by sbender9** [comment]
Can you copy and paste or attach file with those messages in it so I can test them.

**Comment by nealguidry** [comment]
I'm not sure if the file you are referring to is the stream from the cat /dev/ttyUSB0. I'm not getting any errors, I just don't see any data / deltas in the dashboard for that provider like I do on the sample file. I have VNC setup and I can provide the username / password in an email to you if you would rather get into the device.

**Comment by sbender9** [comment]
Let’s start with a file capture of the stream from the device.

**Comment by nealguidry** [comment]
here is a text file with the stream. 
[nmea stream.txt](https://github.com/SignalK/signalk-server-node/files/2931853/nmea.stream.txt)

**Comment by sbender9** [comment]
These sentences are not recognized by our 0183 library. They do not look like valid 0183 messages to me and I can't find any reference to a `POS` sentence anywhere.

What 0183 device do you have hooked up to this?

**Comment by nealguidry** [comment]
The system is an ECDIS. http://www.ecdis-info.com/about_ecdis.html

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=8&ved=2ahUKEwjm-pX63-vgAhVJ7qwKHWKDAK8QFjAHegQIBBAC&url=http%3A%2F%2Fwww.transnav.eu%2Ffiles%2F10%2520Things%2520They%2520Should%2520Have%2520Told%2520You%2520About%2520ECDIS%2C9.pdf&usg=AOvVaw2edWAvUY2rADU6QsP4jIg4
![img_8471](https://user-images.githubusercontent.com/2716325/53832767-a59b6600-3f4c-11e9-8465-e5d2d50169ee.JPG)
![img_8470](https://user-images.githubusercontent.com/2716325/53832768-a59b6600-3f4c-11e9-96cb-7ce722098fc1.JPG)


Marine data is transferred using the NMEA 0183 standard, which is a simple ASCII (ie text) format that defines how data is transferred in a sentence from one instrument to another, eg:
$GPDTM,W84,,00.0000,N,00.0000,E,,W84*41 $HEHDT,340.8,T $GPGLL,5120.5091,N,00312.7769,E,090813,A*2D
Most sentences begin with a $ followed by a two character talker ID. In the foregoing data, GP is GPS and HE is Gyro. Then follows a three character sen- tence identifier: DTM is datum; HDT is heading, and GLL is geographic position, latitude and longitude. Even without a knowledge of sentence structure you can extract some meaning from each
4 “the collection, integration and display of maritime information aboard and ashore by electronic means to enhance berthto-berth navigation and related services, safety and security at sea, and the protection of the marine environment” definition from the International Association of Marine Aids to Navigation Lighthouse Authorities (IALA).
 
sentence, eg, the heading above is 340.8°T and latitude 51°20.5091’N.
!AIVDM,1,1,,B,35Vi7f50000AEw<M@ee;wCLB00 00,0*3B

**Comment by sbender9** [comment]
I don’t see any of those sentences mentioned in the log file you attached. I think the usg-2 might be doing some translation. I can’t find any info that.

**Comment by tkurki** [comment]
Saying that it is an ECDIS provides about as much useful information as saying it is a _computer_.

The supported sentences are listed at https://github.com/SignalK/signalk-parser-nmea0183/blob/master/README.md. Your sample data has none of those, so there is no Signal K output.

**Comment by nealguidry** [comment]
Well at least I know what needs to be done now. I'll have to get into the ECDIS unit and try to modify the nmea sentences to match signalk. I'll post an update if I get this working. Thanks for the assistance.

**Comment by sumps** [comment]
The POS sentence is a valid NMEA0183 sentence just not that common on pleasure craft. It allows a positioning device to specify the size of the vessel and the position of the GPS antenna - like you do when setting up a Class B transponder.

Think you should support it.

**Comment by sbender9** [comment]
Do you have details on it? I was unable to find any.

**Comment by nealguidry** [comment]
Had to choose the correct data source in the ECDIS. Once I chose the correct settings in the dropdown the nmea stream works and is now being logged by signalk server.
