### ISSUE TITLE
Server crash when client resets connection

### ISSUE THREAD

**Issue by mairas** [SignalK/signalk-server-node#751]
When beginning to implement token authentication in [SensESP](https://github.com/mairas/SensESP), I ran into the following:

If I feed an invalid JWT token to the websocket endpoint, the server crashes. A sample request, captured with `tcpdump` on the server:

```
GET /signalk/v1/stream?subscribe=none HTTP/1.1
Host: 192.168.9.134:80
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: 3D/tJftsWmmVONQ8lhVMgg==
Sec-WebSocket-Protocol: arduino
Origin: file://
User-Agent: arduino-WebSocket-Client
Authorization: JWT 123456

```

and the result on the server log:

```
Mar 17 18:07:25 hurma signalk-server[31856]: signalk-server running at 0.0.0.0:[object Object]
Mar 17 18:07:26 hurma signalk-server[31856]: events.js:174
Mar 17 18:07:26 hurma signalk-server[31856]:       throw er; // Unhandled 'error' event
Mar 17 18:07:26 hurma signalk-server[31856]:       ^
Mar 17 18:07:26 hurma signalk-server[31856]: Error: read ECONNRESET
Mar 17 18:07:26 hurma signalk-server[31856]:     at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Mar 17 18:07:26 hurma signalk-server[31856]: Emitted 'error' event at:
Mar 17 18:07:26 hurma signalk-server[31856]:     at emitErrorNT (internal/streams/destroy.js:82:8)
Mar 17 18:07:26 hurma signalk-server[31856]:     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
Mar 17 18:07:26 hurma signalk-server[31856]:     at process._tickCallback (internal/process/next_tick.js:63:19)
Mar 17 18:07:26 hurma systemd[1]: signalk-server.service: Main process exited, code=exited, status=1/FAILURE
```

I would have expected to receive an HTTP 401 error instead.

**Comment by tkurki** [comment]
Now that I have my brains out: that looks like the client reset the connection. Can you repro this?

The server should naturally be able to handle this and not fall over.

**Comment by mairas** [comment]
Yes, it happens consistently. I don't think the client is resetting by itself, though, because at that point adding the Authorization header was the only change I made to previously working code.

**Comment by tkurki** [comment]
```
curl -i -N \
-H "Connection: Upgrade" \
-H "Upgrade: websocket" \
-H "Host: localhost:3000" \
-H "Sec-WebSocket-Version: 13" \
-H "Sec-WebSocket-Key: 3D/tJftsWmmVONQ8lhVMgg==" \
-H "Sec-WebSocket-Protocol: arduino" \
-H "Authorization: JWT 123456" \
-H "Origin: https://www.websocket.org" http://localhost:3000/signalk/v1/stream
```
with security enabled and readOnly disabled just gives me 

```
HTTP/1.1 401 Unauthorized
Connection: close
Content-Type: application/json
Content-Length: 32

{"error":"Invalid access token"}
```

**Comment by mairas** [comment]
Yep. :-( I couldn't replicate it with Postman either. I can poke around a bit later, maybe be doing a proper recording with tcpdump and analyzing it with Wireshark.

**Comment by tkurki** [comment]
What if you "break" the Authorization header to something like just misspelling Authoriaztion - assumption being that this is the client crashing with just a little longer message.

And if you have great ideas about how to induce Connection reset by peer on the server's ws connection please share...

**Comment by mairas** [comment]
Here's a tcpdump capture file that can be opened with Wireshark. The file contains a couple of server restarts in a loop. SK server is 192.168.9.134, ESP8266 running SensESP is on 192.168.9.130.

Not quite sure how to interpret that - the approx. 5 second delay IMO should correspond to server restart, but why would the server continue the same TCP connection then?

[sensesp.tcpdump.zip](https://github.com/SignalK/signalk-server-node/files/2979988/sensesp.tcpdump.zip)

**Comment by tkurki** [comment]
![image](https://user-images.githubusercontent.com/1049678/54561013-59303b80-49cc-11e9-8959-461f5ea7aa5c.png)

In the pic there are two connections with the same sequence:
- establish tcp connection (three way handshake)
- client requests /signalk/v1/stream?subscribe=none
- server responds with 401 and a nice json payload that says Invalid Access Token
- client resets the connection

**Comment by mairas** [comment]
Doh, thanks for the pic. Should've thunk that.

That was my interpretation as well otherwise, but what about the 5 second delay between packets 8 & 9 and 18 & 19? You'd expect the server to crash immediately after the client reset.

**Comment by tkurki** [comment]
Oh I think I have it - this is port 80, so it is systemd listening on the socket (`[object Object]` ugliness in your server log snippet), not the node server process. It takes 5 seconds for the server to actually start and handle the connection.

Nice puzzle!
