### ISSUE TITLE
Access requests should be idempotent

### ISSUE THREAD

**Issue by mairas** [SignalK/signalk-server-node#753]
IF a device has made an access request that is pending

AND then forgets the request URL and makes a new access request

THEN the server should respond with the same request URL instead of an error.

REASONING: Once the device has forgotten the request URL, it has no way of retrieving it or getting the token if the request has been approved.

**Comment by mairas** [comment]
Just realized this might be a really bad idea security-wise. If you know the clientId, you can get an existing request and steal the token. Feel free to close if this is the case.

**Comment by fabdrol** [comment]
I think it's a bad idea, in any case if a client implements request/response security and forgets the request that's a bug that should be fixed in the client IMO. Please close if you agree ;-)
