### ISSUE TITLE
Feature request: venus-html5-app in SignalK Node Server Webapp

### ISSUE THREAD

**Issue by MichelleWhy** [SignalK/signalk-server-node#757]
I would love to see https://github.com/victronenergy/venus-html5-app as a web app in SignalK Node Server (it even should look nice as a single page within WilhelmSK) with configuration settings for Venus device either locally or in the same network (2nd Pi).

**Comment by tkurki** [comment]
As you can't do anything with the Venus app on an SK server without a Venus device and if you have a Venus you can get the latest and greatest webapp loaded from it. Can you explain a little more the situation when this would be useful?

If you have a client that supports mdns the app is available at  http://venus.local/app. We could leverage that and provide a "dummy" webapp in SK server that actually redirects to the real Venus device's webapp. In SK land there's the Victron plugin, that could do double duty to provide also this minimal webapp.

**Comment by MichelleWhy** [comment]
I run OP/SignalK/NR on one PI while Venus runs on another Pi, both in the same network. Sure I could run the Venus app from its own device, but like to have it all in one place. That may not qualify as useful tho ;-)

Yes, I like what you suggest with a "dummy" webapp in SK. Probably the same what http://localhost:8000?host=localhost&host=<VENUS_DEVICE_IP>&port=9001 does?

Finally I'm striving for the webapp to run or at least display on WilhelmSK as a single page...if I can get the author to work on that. Neatly arranged, nice and clear display for the substantiell electrical system values.

**Comment by sbender9** [comment]
You should be able to add this to WilhelmSK by adding a “Web” gauge and entering http://venus.local/app/ for the url. I will test when I get home...

**Comment by sbender9** [comment]
And I want to just be sure you know that you can install venus plugin and use native WilhelmSK gauges to display anything that is shown on that page (I think everything is in SignalK then)

**Comment by MichelleWhy** [comment]
Ha, didn't know there was a Web gauge. If that is going to work, then please forget about my request.

Yesterday I tried to redirect to the SK machine, but couldn't get that to work. The webpack dev server from the Venus Pi responded, but with a mqtt error message. Venus v2.30~38. The installation of node & npm was a bit of a pain and maybe got something wrong. Will try again for sure.

Yes I know that, Scott, and it's already working pretty nice. Took quite some days to work this out by myself w/o documentation ;-)
But for clarity sake I would prefer the Venus app style.

**Comment by sbender9** [comment]
Yeah, sorry about the documentation issue, one of these days I’ll find time to spend on it... Feel free to reach out if you need any help.

**Comment by MichelleWhy** [comment]
No worries. Meanwhile I get the hang of it. I should write the documentation :D

**Comment by sbender9** [comment]
Works for me. 

![5C7B01C8-D1B3-458C-B9C2-20A09A449050](https://user-images.githubusercontent.com/7853683/54892948-f20dfd80-4e89-11e9-859f-6ebc2923d174.png)

**Comment by MichelleWhy** [comment]
Yes, that's what I wanted it to do. Sweet, thanks!

Which Venus image did you use? Was node.js and npm installed or did you get this nerv wrecking error message about missing package.json? I think you have my email. You can answer me there if you want.

Cheers, Stefanie

**Comment by MichelleWhy** [comment]
See message above.
