### ISSUE TITLE
MQTT, STOMP

### ISSUE THREAD

**Issue by joabakk** [SignalK/signalk-server-node#82]
Am I right in assuming that there is no provision for MQTT or STOMP in the current version?
I find them in the java server, but nothing in the node server.

**Comment by joabakk** [comment]
I have identified mosca as an npm dependency to implement mqtt, but have no clue whaat is required for stomp.

**Comment by tkurki** [comment]
MQTT and STOMP are implemented only on the java server. I'm not sure how much use they've gotten, maybe @rob42 can enlighten us.

@joabakk is there a specific use case you'd like to cover with these?

**Comment by joabakk** [comment]
I saw that. I only heard about MQTT this week when investigating your idea @tkurki. I found this:
https://learn.adafruit.com/mqtt-adafruit-io-and-you?view=all
It seems like a good way for lightweight clients to communicate with the server.

I have no specific need for STOMP, but thought they could be bundled in a common issue, since they may require dependencies and may or may not be related.

**Comment by rob42** [comment]
MQTT is one of the protocols being pushed as ideal for lasrge distributed IoT networks. STOMP is a very simple ASCII protocol for the same, and offshoot of Apache ActiveMQ, one of the major message queuing brokers in java/enterprise land.
There is a large MQTT community effort for IoT, See Eclipse Paho, and https://github.com/rhiot. For the java server its all smiles as it uses Apache camel, which  integrates closely into ActiveMQ and Rhiot.
I added STOMP cos it was easy and its really simple to add to a low-cpu/mem device, being just txt

**Comment by joabakk** [comment]
I think we can close this. Adding data from light clients is fully feasible by other means
