### ISSUE TITLE
Problem installing nodejs 8 in new Raspbian Buster

### ISSUE THREAD

**Issue by sailoog** [SignalK/signalk-server-node#823]
The new Raspbian based on Debian Buster comes with nodejs 10.15.2. Following the [recommended installation with version 8](https://github.com/SignalK/signalk-server-node/blob/master/raspberry_pi_installation.md), the installed version will be always 10.15.2 from raspberry sources. In Raspbian Stretch the node version was 4.8.2 so, version 8 was always installed from node sources.

The problem is that npm is not installed with nodejs 10.15.2 from raspberry sources so you have to install it manually but... npm version in Buster is 5.8.0 which is not compatible with nodejs 10.15.2!

You can force to use the nodesource adding this content to a file /etc/apt/preferences.d/preferences

```
Package: nodejs
Pin: origin deb.nodesource.com
Pin-Priority: 1001
```

But the question is: should we keep https://deb.nodesource.com/setup_8.x in the raspberry installation page adding the preferences file solution or maybe is time to go with https://deb.nodesource.com/setup_10.x?

**Comment by tkurki** [comment]
Yes, let’s move on to 10. Please report anything you may encounter in #546.

**Comment by wouterdebie** [comment]
Since we've upgraded to node 10, we can close this issue
