### ISSUE TITLE
Refresh the app interface with "Server restart" (refresh plugin list, internet connection status etc)

### ISSUE THREAD

**Issue by GaryWSmith** [SignalK/signalk-server-node#832]

**Comment by GaryWSmith** [comment]
Plugins which have been removed (manually) remain listed and survive a server restart. 
Internet connectivity status can be stale and remains stale through a server restart.

Both status' are correctly updated with a logout/login

**Comment by GaryWSmith** [comment]
Newby error closed the issue inadvertently.

**Comment by GaryWSmith** [comment]
Browser refresh (Ctrl + F5) achieves the same thing.
Closing issue as not necessary.

**Comment by tkurki** [comment]
Yes, all parts of the ui should refresh when reconnecting after a server restart. You are not the only first one to be confused about this, so I’ll reopen the issue.

**Comment by wouterdebie** [comment]
Tbh, I'm not sure if this is necessary. It's common for applications to restart and I don't think the UI should reload. I do however think we shouldn't have to restart the server after removing or adding a plugin though.

**Comment by emilecantin** [comment]
I guess we can close this issue, since a fix has been merged?

**Comment by tkurki** [comment]
@wouterdebie some points, a bit overdue:
- making everything work 100% correctly when removing something is a lot of work to solve a somewhat minor nuisance and I suspect we would anyway end up with _please try restarting everything_ replies anyway when responding to problems
- Express does not provide a way to unregister routes
