### ISSUE TITLE
Build problems on Ubuntu 16.04

### ISSUE THREAD

**Issue by GaryWSmith** [SignalK/signalk-server-node#838]
Building on Ubuntu 16.04 using "sudo npm install -g --unsafe-perm signalk-server" results in a stream of errors. Although a binary is created it is missing functionality.

[error.zip](https://github.com/SignalK/signalk-server-node/files/3439322/error.zip)

**Comment by tkurki** [comment]
The log you have attached is not a result of `sudo npm install -g --unsafe-perm signalk-server`, it is from running `bin/n2k-from-file`.

The error concerns just the n2k demo data and is actually fixed in master  #820 , thanks for reminding me that we do need a new release.

**Comment by GaryWSmith** [comment]
[builderror.zip](https://github.com/SignalK/signalk-server-node/files/3448254/builderror.zip)
Sorry, here is the correct log file

**Comment by tkurki** [comment]
It looks like you have Node JS 12.6.0 installed. We are just now making the transition from version 8 to 10.
