### ISSUE TITLE
Server Plugin Config Submit button should clear persistent data 

### ISSUE THREAD

**Issue by GaryWSmith** [SignalK/signalk-server-node#840]
Repeated presses of the Plugin Config Submit Button causes duplication of objects. This possibly only affects arrays i.e. where lists are created on the web UI.

Although the objects are never repeated on the Plugin Config page, the plugins are handed duplicates. Each button press causes the doubling of the list.

Removing items from the UI list does not remedy the problem - until the list is emptied at which time the persistent data appears to be cleared.   

Suggested remedy - clear the persistent storage before committing new values from the web UI.

**Comment by tkurki** [comment]
I can not replicate this. Each configuration update from the UI totally replaces the file used for persisten storage. 

My guess is that your plugin is not handling `stop` properly and when each submit from the plugin config user interface stops and starts the plugin the data gets duplicated somehow. 

The default location for each plugin's config data is in $HOME/.signalk/plugin.config-data, with separate JSON files for each plugin. You can check what happens there when you submit repeatedly from the UI.

I am going to close this, feel free to reopen if additional debugging is needed. You can also share a pointer to your code, I may be able to see what is going on there.
