### ISSUE TITLE
Data Log files

### ISSUE THREAD

**Issue by nealguidry** [SignalK/signalk-server-node#842]
It appears that a new log file is being created every hour. How do I see the entire trip/journey  for the entire day, without having to manually open each log file?

**Comment by tkurki** [comment]
What exactly do you want to see - your track, minimum/maximum values for some data points or for example the length of your track?

There is nothing that I am aware of that would do that out of the box. 

Have you looked at the log files at Server's Admin UI: Server => Data log files? It lists all the log files and in addition to links for downloading it has links to https://www.chartedsails.com/, where you can play back the data file and plots a track, but that is also by hourly file.

If you are storing all the data in InfluxDB with the plugin the server has an API for accessing past data and https://www.wilhelmsk.com/ can play your data back using that.

**Comment by nealguidry** [comment]
I am using the Server's Admin UI: Server => Data log files. I see the buttons which are hourly. Currently the log files are stored in the default location in the root of the signalk folder but I would like to store the data files elsewhere. Either on an external usb drive or use a cron job to move the files to a server. I like how the chartedSails works, just wish I could combine all the data files for that day into one file so that it will track the entire course not just hourly. At the end of the day I could have a history. Or, use the InfluxDB that you mentioned. I already have the WilhelmSK app on my iPhone. I just installed influxdb and created a database, named it signalkdb and put the database name in the database field in influxdb writer section settings. Not sure what to do next? is there any kind of documentation on this integration?
![Screen Shot 2019-07-30 at 1 43 35 PM](https://user-images.githubusercontent.com/2716325/62156227-32660800-b2d0-11e9-9894-7d5bd3767740.png)

**Comment by tkurki** [comment]
I have not used the feature myself, but I am sure Scott will help you here in time. There is a setting in WSK for showing track with time window length and resolution parameters.

**Comment by nealguidry** [comment]
thanks very much for the info. I'll check with Scott.

**Comment by tkurki** [comment]
So the issue here would be an option to produce a single log file per day? And _per day_ should local time, not UTC time.

If that is the case then let's close this one and add a more compact issue for that.
