### ISSUE TITLE
Install from source

### ISSUE THREAD

**Issue by kledom** [SignalK/signalk-server-node#858]
The readme says that I should run
```
git clone https://github.com/SignalK/signalk-server-node.git
cd signalk-server-node
npm install
```
to install from source. However, if I do so the packages @signalk/stream and @signalk/server-admin-ui are installed from the npm repository and not from the local files in ./packages. How do I fix this problem?

**Comment by tkurki** [comment]
Run `npm link` in both directories under packages/  and `npm link @signalk/stream` and `@signalk/server-admin-ui`. If you think documenting or automating this is worth the effort a PR would be very welcome.

**Comment by kledom** [comment]
Thank you for your fast reply! Sorry for the dumb question, but it's the first time I'm confronted with JavaScript and node.js.
