### ISSUE TITLE
Login username case sensitive

### ISSUE THREAD

**Issue by fencer** [SignalK/signalk-server-node#866]
When loging in to admin dashboard, the username is case sensitive. 
Steps to reproduce:

1. Create User eg: `User123`
2. Log out of admin
3. On the login screen input `user123 `as username (all in lower) & the correct password.
4. A message will display saying the username is invalid.

**Comment by sbender9** [comment]
I don’t think this an issue. It is case sensitive by design.

**Comment by fencer** [comment]
Interesting! My opinion is that it should be case insensitive like the vast majority of the online portals making more user friendly. But that's just my opinion :)

**Comment by sbender9** [comment]
I get it, but IMHO, username is just another secret like a password. Case sensitivity can make it harder to guess. Unless/until we implement two factor authentication, i’d prefer we keep it this way.
