### ISSUE TITLE
signalk cannot get webapps to start. 

### ISSUE THREAD

**Issue by Alan788** [SignalK/signalk-server-node#868]
Following your instructions, have signal k installed on a RPi 3b. First pi project. Cannot get the webapps to start. Either at home or on my sailboat. At home, using a the pi standalone with a TV as a monitor.  On the boat, remote desktop connection to the Pi. Demo will not work either get firewall or proxy blocking message. Demo does work on this android tablet. 
Obviously missing something. Is there a command to start the webapps interface?

Have the pi set to use remote desktop in win 10 on the boat. 
Have a n2k network on the boat, with an actisence ntg-1 gateway. Want to use opencpn on the laptop, and get signals to this tablet as well.

Any suggestions?

Thank you

**Comment by tkurki** [comment]
I really don't know where to start here.

Which instructions have you followed?
When you say _Cannot get the webapps to start_ what do you mean? Webapps don't really start, you load them in a browser and they start working - what exactly are you trying and what exactly is failing?

What demo are you referring to exactly? When you say the demo works on an android tablet what exactly is working there?

As there is no firewall or proxies involved in normal installations I have no idea where those error messages are coming from. Maybe a screenshot would help?

As for OpenCPN, N2K and NGT-1 you should
- configure NGT-1 input in SK server
- activate relevant Signal K to NMEA0183 conversions in the plugin config and activate the plugin
- add a tcp connection in OpenCPN to port 10110 with the address of the host running SK server (or localhost if they are on the same machine)

**Comment by Alan788** [comment]
Thank you very much for your e-mail. Not easy to describe  problems like this. 

 

I’ll go through the steps I did. 

 

1.	Installed the operating system and set up the Pi. TV for a monitor, keyboard etc. found out its wireless will not connect at home, had to go old school on my wired network. It will connect to the marinas network. 12mps network. 
2.	Found the githhub site, created an account and installed signal k.  for raspberry https://github.com/SignalK/signalk-server-node/blob/master/raspberry_pi_installation.md, starting at the install signal K.  

 

3.	Because I wanted to connect the pi to this laptop for setup on the boat, I set up wn10 remote access, following this site: https://thisdavej.com/beginners-guide-to-installing-node-js-on-a-raspberry-pi/#comment-6746

 

4.	On the boat, loggd in with remote connection, I set up signal k (ran setup again) and added boats name and mmsi. 

 

5.	If I click on http://127.0.0.1:3000/, I get a message connection blocked, check proxy or firewall. . I tried this at home hooked up to the tv, and get the same result. 

 

6.	If I click the above link on my tablet, I get a demo of the dashboard or menus. 

 

7.	 

 

8.	I’m not getting the menu or dashboard as outlined in the link to installing signal on a Pi. 

 

Tried the section on nema 2k. ran dmesg | grep -i 'usb' get:  FTDI USB Serial Device converter now attached to ttyUSB0

 

I hope this helps. I can try to get screenshots tomorrow or later tonight. 

 

Alan

**Comment by tkurki** [comment]
If you ran `signalk-server-setup` your SK server is most probably running on the default port and accessible at http://127.0.0.1/.

**Comment by Alan788** [comment]
Thanks very much

 

Had some time yesterday on the boat, and ran through some things. Copied the results.  

Have not had a chance to try at home again with the Pi hooked up to the tv. 

 

I did try that port again several times. 

Attached a word file with what I have done so far. 

 

Alan

**Comment by Alan788** [comment]
Good evening. 

 

I let the Pi sit for other priorities.  Back at it tonight. Went and bought another micro sd card, and stating on the following page: https://github.com/SignalK/signalk-server-node/blob/master/raspberry_pi_installation.md

Went from downloading and installing the operating system onwards. 

1.	Radically different behaviour than with the raspberry operating system that came with the kit. 
2.	Setup also connected to my wifi network which did not happen before. 
3.	Node js installed the installed signal. Lots of lines of code , did not see that much on the other sd card. 
4.	Tried the sample nmema 0183 data.  Fails. Looking for dependencies that need to be manually installed. Not sure what dependencies its looking for nodejs or signalk. Warning says npm react-markdown@4.2.2 <mailto:react-markdown@4.2.2>  requires a peer of react@^15.0.0 <mailto:react@%5e15.0.0>  || ^ 15.0.0 but non is installed. You must install peer dependencies yourself. 

 

Not sure what its looking for. Ight you be able to point me in the direction of the peers?

 

Not a linux user, been on the Microsoft tract since dos 1.0.

 

Not getting the signalk menu yet. 

 

Wonder if part of the problem before was the operating system, and linking to a windows machine so as not to have to use a TV?

 

Thank You

 

Alan

**Comment by tkurki** [comment]
The warnings about missing peers are not errors and you don't need to fix them.

I don't think I can give good enough advice over email/github issue if you have no linux experience. I suggest you try to find somebody local who is more knowledgeable about linux / raspberry pi in general who can help you out.

**Comment by Alan788** [comment]
Thank you very much. the fact that the warnings are not errors are a big help. 

I’ll keep plugging along with it. A good challenge. Which I why I got the Pi in the first place.

 

its difficult trying to help at a distance. Especially when I’m new to linux.  I really appreciate your assistance, its been a tremendous help.  

When I get it going, will let you know, as the solution may help you. Probably something I’m missing. 

 

Alan

**Comment by Alan788** [comment]
Would it be possible to get a file containing nema 0183 data or nema 2000 k data?  

 

Finally got back at working on the Pi. Having a terrible time trying to get signal K working. Spent equivalent of days  on it. Have  redone everything multiple times. Am now getting something weird. 

 

Had been using a Samsung led tv as a monitor, and after putting in a smart tv, started getting different errors. 

Found an old vga led computer monitor and bought an vga to hdmi adapter. 

 

Get totally different errors now. 

 

Following step by stem from this site. 

 

Raspberrian is up to date, nodejs ver 13, . https://github.com/SignalK/signalk-server-node/blob/master/raspberry_pi_installation.md

 

Freshly reinstalled signal k. start the server. 

 

When I type in http://127.0.0.1:3000/signalk   I now get a chromium message 

 

“Check your internet connection 

Etc

Allow Chromium to access the network in your firewall or antivirus settings etc

 

If you use a proxy server

Check your proxy settings etc. “ don’t use a proxy. 

 

Far as I can tell there is no firewall in the Pi. There is a possibility that the wireless router is an issue. However if I use chromium on the Pi, I can surf anywhere. 

 

Got to be one of the strangest problems I have ha din over 40 y of working with the darn things. 

 

Alan

**Comment by tkurki** [comment]
Nodejs should be version 10, 13 probably does not work.

**Comment by Alan788** [comment]
Thanks very much.  Can go back to 10. It was 10.x until yesterdays trials. Probably will format the sd card and go back playing with it from the start. Also bought a Raspberry  7 inch screen for the boat. 

 

Know I have a very odd wireless network problem in the house. No idea if they are related. Samsung  Android tablet and smartphones email will not download when connected here, go to a restaurant with wifi, they work perfectly. Samsung says it’s the internet providers wireless router, the ISP says its Samsung’s issue. Internet works perfectly on a browser at home. Somewhat similar to the Pi. Goes to a site, e.g. Signalk, read, etc., but the pi will not connect to the demo data.  Email provider tech people have gone over the settings many times and they are correct. 

 

Worked properly until December last year. Have to wonder if an  update was made to the router, and causes a problem. 

 

If there is a conflict here I may not get anywhere until May when the boat goes in the water. 

 

I am a retired University Prof, and have taught  various boating courses for Canadian Power and sail squadrons, entry level through celestial navigation for almost 30 years.  If you need someone to help test things in signal K or navigation, I’m willing to try. Not sure how much help on programming I can offer, everything I have done until the Pi has been on windows in recent years. 

 

Alan
