### ISSUE TITLE
Charted Sails website

### ISSUE THREAD

**Issue by nealguidry** [SignalK/signalk-server-node#876]
This was working until a couple days ago. Looks like the site https://www.chartedsails.com is down. I have my logs being saved and opening the signalk log file in the charted sails website to view the trip. Anyone know what's going on with it?

**Comment by tkurki** [comment]
Ping @sarfata 

Chartedsails has pivoted and can no longer display uploaded SK log files, so I think we should remove the link from the admin UI page.
