### ISSUE TITLE
Deltas with thousands of paths make server unresponsive

### ISSUE THREAD

**Issue by TensionSoftware** [SignalK/signalk-server-node#877]
I have manually sent to the signalk server a large number of paths via a delta.

I ran a loop to create the delta which has 1 update with 6000 different value/path combinations. The paths are test.xx where xx is the iteration number from the loop. The values are xx * 2 where xx is the iteration number from the loop. This leaves me with 6000 paths in signalk from test.0 to test.5999 with values from 0 to 11998. I only send this delta 1 time about 1 second after the server starts.

I can see on the dashboard that the path count goes up to 6000. I can go to http://127.0.0.1:3000/signalk/v1/api/ and see the list of paths but this only works for a few seconds after adding this many paths.

After a few seconds the server becomes unresponsive. I do not get timeouts from the server but appear to get messages about waiting for socket. 

I am not sure what logs can be useful in troubleshooting this so please let me know what else I can add to this.

I am running the server on a Raspberry PI 4 with 4GB ram running from an SSD drive plugged into USB. This setup has worked very well for several weeks. I normally only have ~100 paths so this issue has not come up. Now I am looking to add a device that has just over 5000 data points to the signalk server but it keep crashing.

Thank you for any help!

**Comment by tkurki** [comment]
You are certainly stressing the server in an unusual way. I don't think logs will help you debugging the exact cause of the problem.

I am not exactly jumping up and down from eagerness to debug this issue, as this is certainly beyond anything I have envisioned as a reasonable workload for the server.

Have you tried sending the data in smaller batches?

**Comment by tkurki** [comment]
I assume reboot in the title does not really mean a reboot of your RPi, just that the sk server becomes unresponsive.

**Comment by TensionSoftware** [comment]
I haven't tried sending it in batches no. That is something I can try next.
The server seems to be able to take the data and even allows me to see it for a few seconds using various methods. In fact as long as I do not try to refresh the web page it seems to work for at least a minute or more.

Once the page gets refreshed or I try to access another app within the signalk server it stops responding.

I do mean just rebooting the signalk server.

**Comment by TensionSoftware** [comment]
for reference, in your mind, what is a normal number of paths?

**Comment by tkurki** [comment]
Maybe a hundred paths for self and say 100 (AIS) other vessels with about 10 paths per vessel.

Which is not that far off from what you are doing, now that I say it.

**Comment by tkurki** [comment]
So let's see if we can do something about this. 

My first theory is that the rate of input is simply too high: if it takes more than a second to process what you are sending per second the server will be overwhelmed, spend all its time processing input and not be able to respond to user's requests. Here smaller batches would help, as JavaScript is single threaded and will block everything else for the duration of handling a single message.

Can you easily share your stress test client?

How will your real data be shaped & how do you plan to use it? This matters a lot. A practical example: now the server is updating a full data structure in memory all the time. If this is not needed (you don't use the http api all the time) we can create the full model only as needed.

What paths will your real data use? as a lot of data for a single path is different from a lot of data with different paths.

How do you plan to use the data? How often? Streaming or http api, single values or all the data a time? Subscriptions?

**Comment by TensionSoftware** [comment]
The test case I built only sends 6000 paths in a single update one time. It does not continue to send updates after that so once the server has processed through the update delta with the 6000 paths it should not longer be doing work expect serving the data to other devices because the data isn't changing. That's not to presume that I understand the under the hood server because I have not gotten into the source code. I set it up that way with the theory that processing that many updates repeatedly would likely not work due to the single threading.

Unfortunately, I think it might be difficult to share the test client since it is part of my active server configuration. A good setup would be to create a clean signalk server then insert one update delta with 6000 path/value combinations. This should have the same impact.

I have several internal devices, as expected that are reporting to signalk through various means. (USB GPS, BME280s, MPU-9255, seatalk networked devices, and a few NMEA devices. I believe that I have a total of 50-75 paths on a normal day. I am looking to add my electrical system data which is from Outback Power Systems. I have an AXS port reading Modbus TCP data from the AXS port.

I setup the signalk node red package and do various manipulations and data passing there. I built a node that opens the connection to the AXS port and polls it. The data stream that I get back includes various number of points from each device. In total I have maybe 750-1000 points. In my node I have created an object to contain the data which includes information about the data such as description, modbus address for each point, raw value, enumerated value, etc.

When I read the data from the node red node that I created it reports a JSON object with a child of each device. Each device has children for each data point from the device such as voltage, current, etc. Each data point has children such as rawvalue, value, description, modbus address, etc. If you look at only the lowest children in the tree of data you end up with a total of ~5000 total points. 

When I first ran this process it collapsed everything. I quickly realized that I was sending the entire 5000 point delta every 250mS. I made some modification and got to a point where it would let the server start, wait 30 seconds, send the entire block of data, wait another 30 seconds, then only send data that had changed from its last state. I am keeping the current state of data in the node red global variables area. 

If I stop the node red node from passing the data to the signalk server and instead send it to a debug node it works without issue. I see the initial send which has a large block of data then on each subsequent delta I see maybe 5-10 data points that have value changes.

I tried send the data points (voltage, current, etc) as objects with their children attached but it did not allow me to access the children easily from other applications.

What I am hoping to get from this is the means to both get the power system data for logging and various display purposes (grafana, infludb) but also to then write a UI that will run on a raspberry pi that has a similar look and feel as you would get from the Raymarine i70 devices. I want it to be able to connect to the singalk server and display various screens of data including all of the control and manipulation of the power system.

To be clear about the data structure I have:
{ "64110" : 
  {"DID" :                        //This is the data point from the device.
    { "value" : "64110", "rawValue" : "64110", "Description" : "Device ID", "Offset" : 1, "len", 1, "type" : 
      "unit16", "writeable" : true, "scaleFactor" : 0, "waitingWrite" : false, "writeValue" : null 
    }  //These are the children of the data point created as a structure to handle enumeration and 
       //writing values
  }
  {"Voltage" : 
    { "value" : "133", "rawValue" : "133", "Description" : "DC Battery Voltage", "Offset" : 2, "len", 1, 
      "type" : "unit16", "writeable" : true, "scaleFactor" : 1, "waitingWrite" : false, "writeValue" : null 
    } 
  }  
}

**Comment by tkurki** [comment]
Is this still a problem and something we should investigate?

**Comment by TensionSoftware** [comment]
I am still having issues with it. I have moved to only using around 500 delta and its working fine but when you get much higher it causes server to crash.

Jason Protzman
Director of Software/Controls Engineering
Tension Packaging & Automation
Cell: (303) 834.7480

“I do not think there is any thrill that can go through the human heart like that felt by the inventor as he sees some creation of the brain unfolding to success" - Nikola Tesla
On Dec 25, 2019, at 4:15 AM, Teppo Kurki <notifications@github.com<mailto:notifications@github.com>> wrote:

Is this still a problem and something we should investigate?

**Comment by tkurki** [comment]
Tried with a single delta:

```
  const delta = {
    updates: [
      {
        values: []
      }
    ]
  }
  for (i = 0; i < 15000; i++) {
    delta.updates[0].values.push({
      path: `navigation.p${i}`,
      value: Math.random()
    })
  }
```
and the server remains responsive, no crashes, ws and http interfaces working. This is on MacOS with plenty of memory.

Can you provide more details to reproduce your problem?

**Comment by valyala** [comment]
If path updates are stored in InfluxDB, then it would be great trying [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/) instead of InfluxDB. It should use much lower amounts of memory and works faster when storing big number unique time series to it - see [this benchmark](https://valyala.medium.com/insert-benchmarks-with-inch-influxdb-vs-victoriametrics-e31a41ae2893).

VictoriaMetrics accepts data in InfluxDB line protocol - see [these docs](https://docs.victoriametrics.com/#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf), so it should be quite easy substituting InfluxDB with VictoriaMetrics at data ingestion path. As for querying path, VictoriaMetrics supports [Prometheus querying API](https://docs.victoriametrics.com/#prometheus-querying-api-usage) and [various export APIs](https://docs.victoriametrics.com/#how-to-export-time-series).

VictoriaMetrics also provides [vmagent](https://docs.victoriametrics.com/vmagent.html) component, which can be used at signalk-gateway for collecting and proxying the data to a centralized signalk-server.

**Comment by tkurki** [comment]
I think very few people will see your message. [Signalk-to-influxdb plugin is separate](https://github.com/tkurki/signalk-to-influxdb), you can try how it fares with VictoriaMetrics as a backend. Then a "how to" type blog post, shared for example on in "Raspberry PI on boats" facebook group would be my next promotion step.
