### ISSUE TITLE
Improve startup log messages

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#884]
When the server starts up it emits some messages that are confusing to people. Warnings either should be clearly labeled as warnings or better yet replaced with human oriented messages. And [object Object] is just 🤦‍♂ .
```
pi@openplotter:~ $ cat /var/log/syslog | grep -i 'signalk-server'
Oct 2 14:15:36 openplotter signalk-server[372]: Could not parse security config
Oct 2 14:15:36 openplotter signalk-server[372]: ENOENT: no such file or directory, open '/home/pi/.signalk/security.json'
Oct 2 14:16:09 openplotter signalk-server[372]: signalk-server running at 0.0.0.0:[object Object]
```

http://forum.openmarine.net/showthread.php?tid=1955&pid=10454#pid10454

**Comment by tkurki** [comment]
Oh. This is how OpenPlotter starts by default: security is on in `settings.json` but there is no `security.json` yet. The user needs to try to login and then create the admin user and security.json with it. This error message will then go away.

**Comment by dpreuss** [comment]
Perhaps a change has cause a fatal error now. 

Could not parse security config
Apr 25 09:26:40 rpi signalk-server[5305]: ENOENT: no such file or directory, open '/home/pi/.signalk/security.json'
Apr 25 09:26:41 rpi signalk-server[5305]: /usr/local/lib/node_modules/signalk-server/node_modules/bindings/bindings.js:121
Apr 25 09:26:41 rpi signalk-server[5305]:         throw e;
Apr 25 09:26:41 rpi signalk-server[5305]:         ^
Apr 25 09:26:41 rpi signalk-server[5305]: Error: libnode.so.64: cannot open shared object file: No such file or directory
Apr 25 09:26:41 rpi signalk-server[5305]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
Apr 25 09:26:41 rpi signalk-server[5305]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Apr 25 09:26:41 rpi signalk-server[5305]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Apr 25 09:26:41 rpi signalk-server[5305]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Apr 25 09:26:41 rpi signalk-server[5305]:     at Module.require (internal/modules/cjs/loader.js:692:17)
Apr 25 09:26:41 rpi signalk-server[5305]:     at require (internal/modules/cjs/helpers.js:25:18)
Apr 25 09:26:41 rpi signalk-server[5305]:     at bindings (/usr/local/lib/node_modules/signalk-server/node_modules/bindings/bindings.js:112:48)
Apr 25 09:26:41 rpi signalk-server[5305]:     at Object.<anonymous> (/usr/local/lib/node_modules/signalk-server/node_modules/@serialport/bindings/lib/linux.js:2:36)
Apr 25 09:26:41 rpi signalk-server[5305]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Apr 25 09:26:41 rpi signalk-server[5305]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Apr 25 09:26:41 rpi systemd[1]: signalk.service: Main process exited, code=exited, status=1/FAILURE
