### ISSUE TITLE
NMEA 0183 data not used as expected

### ISSUE THREAD

**Issue by pgrawehr** [SignalK/signalk-server-node#936]
It might be a small thing, but I just don't get this to run as expected with NMEA 0183 data. 

Setup:
- Signalk-server-node, with freeboard, installed on a Raspberry Pi
- I've added all plugins to make navigation work, including @signalk/freeboard-sk, @signalk/signalk-to-nmea0183, sk-resources-fs and freeboard-sk-helper
- With Signalk's own NMEA 0183 simulation file, it mostly looks fine: the position is show on the map, and the instrument panel shows values (except the cross track error stays 0, although I've set a route - but that could be because the simulation already provides an XTR dataset - so I assume this is a simulation artifact)
- Now I set up an external NMEA 0183 simulator (used https://chrome.google.com/webstore/detail/nmea-simulator/dfhcgoinjchfcfnnkecjpjcnknlipcll, but probably about anything will do)
- I set up the simulator on the PC as a TCP server. It just follows a straight line. A small sequence of messages is attached. 
[NmeaSim.txt](https://github.com/SignalK/signalk-server-node/files/4099339/NmeaSim.txt)

- Then I set up signalk to connect to the simulator using TCP
- The connection works, the ship is placed as expected
![grafik](https://user-images.githubusercontent.com/13809874/72923619-bbc23880-3d4f-11ea-8739-b5fabdd1d982.png)
However: None of the controls update any more (or they show no data at all), not even the position, although that one is clearly available. The simulated data also does contain speed trough water and heading information.. None of this is visible in Signalk (the displayed course of 10° is not correct). 
![grafik](https://user-images.githubusercontent.com/13809874/72923833-19ef1b80-3d50-11ea-81f1-d8aef9cd80eb.png)
I really don't know what could be missing to make this work. 
Maybe interesting: Also the VMG and BRG values on the chart screen (visible when a route is active) only update their values after changing the waypoint, but not after the speed of the ship changes.

**Comment by tkurki** [comment]
If I replace `samples/plaka.log` with the data you linked (remove the telnet preamble) and run `bin/nmea-from-file` I get a nice IP display that updates:
![image](https://user-images.githubusercontent.com/1049678/72930678-2336b300-3d65-11ea-8929-c16c911ecb43.png)

and the IP embedded in Freeboard works also
![image](https://user-images.githubusercontent.com/1049678/72931100-f46d0c80-3d65-11ea-90a7-15b1485b286d.png)


Your IP screenshot shows a bunch of data that is definitely not in your sample data: moon and the uuid things. Are you sure the valid data is not hidden under the fold and available by just scrolling? IP remembers the layout and gauges from the previous use unless you reset it from the settings, so the screenshot doesn't really tell me much.

**Comment by pgrawehr** [comment]
The moon data is is generated by the derived-data plugin. That one just needs the time to work. 
You pointed me to the right direction: After resetting the layout of the controls, it started to look better, and here is why:
![grafik](https://user-images.githubusercontent.com/13809874/72935073-f5516e80-3d64-11ea-97ca-bbaa38251f7a.png)
If instead of this control, I use the one bound to "Server1.GP", it works. 
Each of the controls is bound to a specifc data source, and not only to the type of data. So the controls must now be connected to "Server1.GP" ("GP" sentences from connection "Server1"). I need to get this sorted out, because now I have more data than what I'm expecting. I think due to experimenting with different simulators and data sources it now remembers them all, which may cause additional confusion. 
Is there a way to see all available data sources (and delete wrong ones)?

**Comment by tkurki** [comment]
Have you read the IP help?

http://demo.signalk.org/@signalk/instrumentpanel/#2_3_8

**Comment by pgrawehr** [comment]
Yes, but I can't find any information on changing the data source for a particular widget, or how to remove data sources that don't exist any more. 
If the user interface gets confused about which data source to use i.e. for position, I fear that internally, it could also be unclear which data source is to be used for navigation. That's maybe the reason why the data in the bottom left corner of the map screen does still not update correctly, it seems. Also, it does not show cross track error unless I feed that data from externally, which is kind of pointless.

**Comment by tkurki** [comment]
You can not _change the data source for a particular widget_ currently in IP, you can hide unneeded widgets or reset everything so that IP creates widgets for all current data.

Just to clarify: InstrumentPanel and Freeboard are individual webapps, with different authors, that are installed in the server by default. Their behavior may or may not be the same for each data item.

Please open issues where appropriate:
- https://github.com/SignalK/instrumentpanel/
- https://github.com/SignalK/freeboard-sk

This way the correct authors get a notification about the issue. You can add a link there to this issue to provide contexts.

I am going to close this issue, because afai can see there's nothing wrong with how the server handles the data. Feel free to reopen if there is still something server related left open.

**Comment by pgrawehr** [comment]
Ok, thanks for your help. I think this part is solved for me now. 

The other thing that might be server related is - as indicated above - the generation of the navigation data (i.e for the autopilot and external displays, so that the XTR, APB and BW* messages are generated). But I'm not sure whether this is even supposed to work or whether that needs another plugin. I'll report back after further investigation, since without proper input, it was clear that this wouldn't work.
