### ISSUE TITLE
Lost delta from :8375 by upgrading to 1.20.0

### ISSUE THREAD

**Issue by canne** [SignalK/signalk-server-node#939]
Both on RPI Linux pi 4.19.75-v7l and on Window 10 w/ node.js v12.14.1 npm  v6.13.4 upgrading from v1..18..0 to v1.20.0 (on Windows with complete re-installation from scratch) leaded to a situation where my [socket based Signal K Node delta input streamer](https://github.com/canne/dashboard_tactics_pi/releases/tag/untagged-e4845d2f2bd7dc685770) came to a grinded halt on both platforms: no data.

I could not find any announcement from the release note to explain this, so I presume that it is not planned to suppress this optional channel. Is/was there such a plan?

On Linux, for example, one can stop the services and launch
```
signalk-server --sample-n2k-data
```
Independently of my application (stuck on socket read wait), one can launch 
```
curl 0.0.0.0:8375
{"name":"signalk-server","version":"1.20.0","self":"vessels.urn:mrn:imo:mmsi:227346650","roles":["master","main"],"timestamp":"2014-08-15T19:00:07.267Z"}
```
And that's it.

On Windows server some messages are displayed (installation from scratch - it is about the same on the simply upgraded Linux npm but with somewhat less of "unexpected tokens"):
```
signalk-server --sample-n2k-data
Using sample data from C:\Users\Petri\AppData\Roaming\npm\node_modules\signalk-server\samples\aava-n2k.data
signalk-server running at 0.0.0.0:3000

GET /admin/img/favicon.ico 304 12.788 ms - -
GET /vessel 200 37.843 ms - 85
GET /loginStatus 200 2.184 ms - 201
Unexpected token G in JSON at position 0
Unexpected token H in JSON at position 0
Unexpected token U in JSON at position 0
Unexpected token A in JSON at position 0
...
```

**Comment by canne** [comment]
Managed to roll back to v1.18.0 on Windows (by a complete reinstall), now get on Linux the :8375 delta data by pointing to server instance on Windows:
```
pi@pi:~ $ curl 192.168.8.100:8375 | more
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{"self":"urn:mrn:signalk:uuid:e5a702ea-0cb8-42cd-8f06-08c43bb5a4b6","timestamp"
:"2020-01-26T15:51:52.193Z","version":"0.0.1"}
{"updates":[{"source":{"label":"Emu2000","type":"NMEA2000","pgn":127488,"src":"
18"},"timestamp":"2020-01-26T15:51:52.263Z","values":[{"path":"propulsion.port.
revolutions","value":17.566666666666666},{"path":"propulsion.port.drive.trimSta
te","value":0},{"path":"propulsion.port.boostPressure","value":6350000}]}],"con
text":"vessels.urn:mrn:signalk:uuid:e5a702ea-0cb8-42cd-8f06-08c43bb5a4b6"}
...
```
Good, I am not completely blocked! Please take a look, nevertheless, thanks.

**Comment by sbender9** [comment]
It’s because of this change: https://github.com/SignalK/signalk-server-node/pull/922

You now need to send a subscription.

**Comment by canne** [comment]
Fine. Any instructions, anywhere?

On Sunday, January 26, 2020, Scott Bender wrote:
> 
> It’s because of this change: https://github.com/SignalK/signalk-server-node/pull/922
> 
> You now need to send a subscription. 
> 
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/SignalK/signalk-server-node/issues/939#issuecomment-57851766

-- 
Best regards / Cordialement / Parhain terveisin
Petri Mäkijärvi

**Comment by sbender9** [comment]
It’s the same as with WebSockets: https://signalk.org/specification/1.3.0/doc/subscription_protocol.html

**Comment by canne** [comment]
Thanks, you resolve this issue. I am so depressed now that I will not comment anymore, who  cares anyway.

>By default a Signal K server will provide a new WebSocket client with a delta stream of the vessels.self record, as updates are received from sources

My instruments were subscribing on their part by user decision to what was available on the previous delta output. Now, if I am understood correctly, I have to further subscribe to what they want? But from one installation to another, how do I know what is available unless I read everything that is available? Don't expect the instrument user to tell me, they know even less about their own installation than I do.

My great plans just got shattered, I better take a walk. I can't follow you guys.

**Comment by sbender9** [comment]
You can subscribe to everything by specifying an asterisk for the path. It would then work just as it had before.

**Comment by sbender9** [comment]
And you’re welcoming for spending my free time on a Sunday to help you.

**Comment by tkurki** [comment]
>I could not find any announcement from the release note to explain this

![image](https://user-images.githubusercontent.com/1049678/73141134-285b7100-4089-11ea-9e2e-98aaedc2cc85.png)
