### ISSUE TITLE
NMEA0183 Parser cannot parse if there is a character between new line and $

### ISSUE THREAD

**Issue by Thomas-GeDaD** [SignalK/signalk-server-node#970]
Hi,
The Parser cannot parse the NMEA string of an NASA Clipper wind for example.
The NASA CLipper wind sends a NULL (/x00) between new line and $. This seems to be incompatible for the Parser because the parser starts at the beginning of the line and not with the $.
For example:
b'\x00$WIMWV,147,R,0,N,A*21\r\n'
b'\x00$WIMWV,147,R,0,N,A*21\r\n'
Is it possible to implement to start parse at $ and not at the beginning of a new line?
![2020-02-17_11h04_27](https://user-images.githubusercontent.com/54798285/74715984-f378af00-522d-11ea-9179-6737031322e5.png)
![2020-02-17_14h03_10](https://user-images.githubusercontent.com/54798285/74716005-012e3480-522e-11ea-948e-d880659681cc.png)

**Comment by tkurki** [comment]
The code is not very complex, could you have a try at fixing this? I can do it also, just no promises on when.

https://github.com/SignalK/signalk-parser-nmea0183/blob/d91e33f704d7a2277059c11c72285a100f09569c/lib/index.js#L59

**Comment by Thomas-GeDaD** [comment]
Hi tkurki,
i´m not very conform with js. But I give it a try… ;-)
Where is the file stored on my livesystem (Raspberry PI4 Buster)?
@ /home/pi/.signalk/node_modules ?

**Comment by tkurki** [comment]
/usr/local/lib/node_modules/signalk-server/node_modules/@signalk/nmea0183-signalk/lib/index.js

**Comment by Thomas-GeDaD** [comment]
https://github.com/SignalK/signalk-parser-nmea0183/pull/164
hope that is o.k. At me all works fine with that
