### ISSUE TITLE
Start even if nmea tcp port 10110 is busy

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#98]
The server won't start if it fails to listen on port 10110:

Error: listen EADDRINUSE :::10110

**Comment by netAction** [comment]
Usually the server crashes here because it already runs. Starting it twice will not help. I would prefer if it simply exits with a good error message. Apache and Nginx do the same.

The same occurs with port 80 or 3000.

**Comment by tkurki** [comment]
Fixed in 662 for 10110. Server still crashes if the main port is in use, but that is understandable.
