### ISSUE TITLE
on win32 platform incorrect attribute checking of TLS certificate files

### ISSUE THREAD

**Issue by cmotelet** [SignalK/signalk-server-node#982]
In `src/security.js`file the chek of file attribute is always false when file is created with `600` mode.
It's return `-rw-rw-rw-` ans not `-r--r--r--`.
https://github.com/SignalK/signalk-server-node/blob/master/src/security.js#L151-L152

Under Windows 10 for return mode `-r--r--r--` you must create file whith `000` mode !!!
Under Windows 7 for return mode `-r--r--r--` you must create file whith `777` mode !!!
And it's produce a file with `read-only` flag for all.
As explain in node V10 source code below, chmod under Windows is not a good way.
https://github.com/nodejs/node/blob/c6c6665e1c1292be954462276a10b16585633044/deps/uv/src/win/fs.c#L1295-L1313

What is the best way to do PR:
- check `-rw-rw-rw-` on win32 platform ?
- invalidate the check on win32 platform ?
- try a bad hack whith a stupid mode `000` on win32 platform ?
- another way ???

**Comment by tkurki** [comment]
Skip the check on windows. 

There is already at least one instance of win32 conditional logic: https://github.com/SignalK/signalk-server-node/blob/master/packages/streams/execute.js#L56

**Comment by cmotelet** [comment]
Closed via PR#982
