### ISSUE TITLE
Server routes for security are not versioned

### ISSUE THREAD

**Issue by fabdrol** [SignalK/signalk-server-node#995]
The server routes for security are not versioned at this time (i.e. `/security/<whatever>` as opposed to `/signalk/v1/security/<whatever>`. This may pose a problem if mechanisms change for a next major version of Signal K. 

Adding the version at that time is not desirable either, as it will break clients that have the Signal K version number in their configuration.

**Comment by tkurki** [comment]
A spec issue, right?

**Comment by tkurki** [comment]
What `security` routes are you talking about, it is `auth` in the spec? See https://github.com/SignalK/signalk-server-node/blob/master/src/tokensecurity.js#L168 and https://github.com/SignalK/signalk-server-node/blob/master/src/tokensecurity.js#L213

We had them at the root, but added the spec compliant routes also. The ui uses these paths also, so the ones under root could be removed.
