### ISSUE TITLE
Tiny Feature request: Having a config entry for / redirects

### ISSUE THREAD

**Issue by FredericGuilbault** [SignalK/signalk-server-node#996]
Hi, Im working on a web based menu dashboard to prevent user from having to know which web services are served under which ports. I would like to do it as a custom sk-app.   But for this, I would need to be able change serverroute redirection here to my sk-app instead of `/admin` :  https://github.com/SignalK/signalk-server-node/blob/f19edc425a4c7f93b7b1f4da5250730614394f7d/src/serverroutes.js#L46

That would be nice to have a config file entry for choosing the redirect location while still having the admin plugin served under `/admin` of course :)

**Comment by tkurki** [comment]
I believe this is fixed in the linked PR - does this work well enough for you?

**Comment by FredericGuilbault** [comment]
I think it will. The issue will be auto-closed when the pull request will be accepted. I was kinda wait for merge to thx and close.

**Comment by FredericGuilbault** [comment]
I just test it and it work :D Thx to you guys.

For the documentation of the feature, May I suggest to add the line `  "landingPage": "/admin" ` To `settings.json`  To make it exist.
